### ISSUE TITLE
iOS App Self-Hosted Login Issue

### ISSUE THREAD

**Issue by 88kbbq** [invoiceninja/flutter-client#100]
Running the digitalocean instance of invoice ninja, latest update. HTTPS on and running fine. Downloaded the iOS app and select self-hosted login and have set up my secret with a https://my_url.com/api/v1/ping?api_secret=put-my-secret-here and successful. 

The iOS app will not login and will not show any error or message. The information i enter on login just disappears and the app is unusable.

There are no instructions on making any in-app purchases because I can't login to the iOS app, and there is no information on what a paid subscription gets you in your documentation.

Need help to get this working.

**Comment by hillelcoren** [comment]
Are you using the iOS beta, other people have reported issues. If you want to email a screenshot of your login settings to contact@invoiceninja.com it may help.

If you're self hosting there is no in-app purchase, the only option is to buy a white label license in the web app.

**Comment by 88kbbq** [comment]
I figured it out. Users have to press the “e-mail login” button, not just press done. Works now. Thank you!
