### ISSUE TITLE
Demo Mode not working

### ISSUE THREAD

**Issue by Siva123258** [invoiceninja/flutter-client#121]
Hi , 
When I enable Demo mode and run this flutter app , the following error is thrown.
![Screenshot_2020-03-15-22-22-15-339_com invoiceninja client](https://user-images.githubusercontent.com/24939245/76706229-ee632e80-670b-11ea-8481-ac59f30390d2.jpg)

**Comment by hillelcoren** [comment]
Thanks for reporting this! The problem is the static demo data invariably gets out of sync over time. We need to work on a solution which keeps it up to date automatically, it could work well with GitHub actions.

**Comment by Siva123258** [comment]
@hillelcoren Can you please provide static demo data that can be used to run the app temporarily as of now.

**Comment by hillelcoren** [comment]
Sorry, I don't have an updated version available. We'll work to fix this in the future...

**Comment by hillelcoren** [comment]
I've checked in an updated version

**Comment by Siva123258** [comment]
> I've checked in an updated version

Working , thank you so much

**Comment by hillelcoren** [comment]
Glad to hear it!
