### ISSUE TITLE
selfhosted login fails and reports wrong version

### ISSUE THREAD

**Issue by em4nl** [invoiceninja/flutter-client#123]
I'm running version 1.11 of the app on iOS 13.3.1. Login to my selfhosted installation fails with "The minimum version is v4.5.4", though the server is running v4.6.0.

**Comment by hillelcoren** [comment]
Thanks for reporting this!

As a workaround changing 4.6.0 here to 4.5.16 here may help:

https://github.com/invoiceninja/invoiceninja/blob/master/app/Constants.php#L364

**Comment by hillelcoren** [comment]
Sorry for the trouble, a new version is available (v4.5.18).

**Comment by em4nl** [comment]
Thank you for the quick reply! I changed the version number in Constants.php to 4.5.18, login works now.

**Comment by hillelcoren** [comment]
Glad to hear it, thanks for the update!
