### ISSUE TITLE
no access to some modules through mobile app

### ISSUE THREAD

**Issue by torstenlze** [invoiceninja/flutter-client#125]
self hosted invoiceninja v.4.5.18
android app (from playstore) v0.1.57

the access through mobile app to
- invoices
- projects
- quotes
- payments
is not possible. you can only see the endless spinning loading cirlce
the access through webgui is possible and works without any problem so far.
also the modules of
- products
- clients
- tasks
- vendors
- expenses
are available through mobile app.

deleting the cache, data or even uninstall / install the app and reauthentication will not change the behavior. 

what can i do to find out, whats going on here?

**Comment by hillelcoren** [comment]
Sounds like a bug, we'll try to replicate...

**Comment by hillelcoren** [comment]
Do you see any related errors in storage/logs/laravel-error.log

**Comment by hillelcoren** [comment]
If you've downloaded the code from GitHub running `composer install` may fix this

**Comment by torstenlze** [comment]
awesome, that fixed the issue, very much thanks!
do i have to do this every time after a git pull?

**Comment by hillelcoren** [comment]
Glad to hear it! It's only needed if the dependencies change but it's best practice to run it with every update.
