### ISSUE TITLE
build ui issues

### ISSUE THREAD

**Issue by boudgeau** [invoiceninja/flutter-client#127]
hello, the build was failed with the many similar to the following error:
`lib/ui/dashboard/dashboard_chart.dart:206:46: Error: The getter 'headline5' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline5'.
                      style: theme.textTheme.headline5,
`

any help please ?

**Comment by hillelcoren** [comment]
For now you need to use an older version of Flutter, we hope to make it compatible with the latest version this week

**Comment by boudgeau** [comment]
> For now you need to use an older version of Flutter, we hope to make it compatible with the latest version this week

Oh, what version do you recommend ? Currently I am using latest flutter sdk version

**Comment by hillelcoren** [comment]
Sorry, I don't have a specific version which will work. It may be easier to wait for us to resolve it.

**Comment by boudgeau** [comment]
hi, where you able to make it compatible with newer version of flutter ?

**Comment by hillelcoren** [comment]
The develop/master branches should work with the latest Flutter version, the legacy branch most likely will not.
