### ISSUE TITLE
Flutter login fails with deserializing error with app building from source

### ISSUE THREAD

**Issue by keinagae** [invoiceninja/flutter-client#129]
[screenshot removed]

with self hosted invoice-ninja any help

**Comment by hillelcoren** [comment]
If you're using Invoice ninja v4.x you need to use the legacy branch of the codebase

**Comment by keinagae** [comment]
i am using legacy branch to build app and invoice ninja app from app store is working fine

**Comment by hillelcoren** [comment]
I'm not sure, can you please send the error screenshot to contact@invoiceninja.com. I removed it from the GitHub issue because it had private info in it.
