### ISSUE TITLE
Exception trace errors on screen

### ISSUE THREAD

**Issue by dmgucor** [invoiceninja/flutter-client#130]
When trying to use some features of the application (i.e. logging in, editing an invoice) without connection, an error is shown to the user that indicates a SocketException. It could be better to inform the user that there are connection issues, which would give them a hint about checking their network in order to proceed with the functionality.

![edit invoic](https://user-images.githubusercontent.com/30917610/82007392-b86cf880-962f-11ea-8198-1070f1429372.jpg)

**Comment by hillelcoren** [comment]
The message has been improved
