### ISSUE TITLE
Stuck progress notification

### ISSUE THREAD

**Issue by dmgucor** [invoiceninja/flutter-client#131]
If the application doesn't have an internet connection, some funcionalities will show a circular progress indicator nonstop (i.e. signing up), or in the case of refreshing data a loading bar blocks the screen completely without being able to do anything else but restarting the app.

![refreshing data](https://user-images.githubusercontent.com/30917610/82008161-8fe5fe00-9631-11ea-988b-8fb22d394c7f.jpg)

**Comment by hillelcoren** [comment]
Thanks for the feedback, we'll look into it...
