### ISSUE TITLE
apk build error

### ISSUE THREAD

**Issue by keinagae** [invoiceninja/flutter-client#135]
hi when i run run flutter apk build it return error
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  path\invoice-ninja-flutter-legacy\build\share\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
  path\invoice-ninja-flutter-legacy\build\share\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

any help

**Comment by hillelcoren** [comment]
Sorry, I haven't tried building the legacy branch in a while. It's possible something changed and is now out of date. 

Maybe this will help: https://stackoverflow.com/a/51474321

**Comment by keinagae** [comment]
i had tried it out already but no luck
