### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by jesulo** [invoiceninja/flutter-client#142]
Hello good day,  I have this error in master branch.

Compiler message:
lib/ui/app/app_bottom_bar.dart:244:25: Error: No named parameter with the name 'toggleable'.
                        toggleable: true,
                        ^^^^^^^^^^
/C:/development/flutter/packages/flutter/lib/src/material/radio_list_tile.dart:307:9: Context: Found this candidate, but the arguments don't match.
  const RadioListTile({
        ^^^^^^^^^^^^^

Compiler message:
lib/ui/app/app_bottom_bar.dart:244:25: Error: No named parameter with the name 'toggleable'.
                        toggleable: true,
                        ^^^^^^^^^^
/C:/development/flutter/packages/flutter/lib/src/material/radio_list_tile.dart:307:9: Context: Found this candidate, but the arguments don't match.
  const RadioListTile({
        ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\development\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\development\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 49s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jesulo** [comment]
and this when, pub get

C:\Users\jesus\Documents\Ninja\flutter-client-master>flutter pub get
! extended_image 0.7.3-dev
Running "flutter pub get" in flutter-client-master...               1,6s

**Comment by hillelcoren** [comment]
You currently need to use the Flutter master channel to build the app

**Comment by jesulo** [comment]
Hi again, thanks you, now show me this.

Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration to migrate your project.
Launching lib\main.dart on SM G9650 in debug mode...
Running Gradle task 'assembleDebug'...
lib/ui/reports/reports_screen.dart:288:32: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                        child: ElevatedButton(
                               ^^^^^^^^^^^^^^
lib/ui/reports/reports_screen.dart:307:30: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                      child: ElevatedButton(
                             ^^^^^^^^^^^^^^
lib/ui/auth/login_view.dart:646:32: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                        child: ElevatedButton(
                               ^^^^^^^^^^^^^^
lib/ui/settings/account_management.dart:188:18: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
          child: ElevatedButton(
                 ^^^^^^^^^^^^^^
lib/ui/settings/account_management.dart:200:18: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
          child: ElevatedButton(
                 ^^^^^^^^^^^^^^
lib/ui/settings/account_management.dart:234:18: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
          child: ElevatedButton(
                 ^^^^^^^^^^^^^^
lib/ui/settings/tax_settings.dart:122:22: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
              child: ElevatedButton(
                     ^^^^^^^^^^^^^^
lib/ui/group/view/group_view.dart:49:20: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
            child: ElevatedButton(
                   ^^^^^^^^^^^^^^
lib/ui/settings/company_details.dart:330:36: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                            child: ElevatedButton(
                                   ^^^^^^^^^^^^^^
lib/ui/settings/company_details.dart:346:34: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                          child: ElevatedButton(
                                 ^^^^^^^^^^^^^^
lib/ui/settings/company_details.dart:478:30: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                      child: ElevatedButton(
                             ^^^^^^^^^^^^^^
lib/ui/settings/invoice_design.dart:118:24: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                child: ElevatedButton(
                       ^^^^^^^^^^^^^^
lib/ui/client/edit/client_edit_billing_address.dart:133:22: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
              child: ElevatedButton(
                     ^^^^^^^^^^^^^^
lib/ui/client/edit/client_edit_shipping_address.dart:130:22: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
              child: ElevatedButton(
                     ^^^^^^^^^^^^^^
lib/ui/invoice/edit/invoice_edit_items.dart:211:17: Error: 'ElevatedButton' is imported from both 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart' and 'package:flutter/src/material/elevated_button.dart'.
                ElevatedButton(
                ^^^^^^^^^^^^^^
lib/ui/invoice/edit/invoice_edit_items.dart:223:17: Error: 'ElevatedButton' is imported from both 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart' and 'package:flutter/src/material/elevated_button.dart'.
                ElevatedButton(
                ^^^^^^^^^^^^^^
lib/ui/app/document_grid.dart:45:28: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                    child: ElevatedButton(
                           ^^^^^^^^^^^^^^
lib/ui/app/document_grid.dart:62:26: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                  child: ElevatedButton(
                         ^^^^^^^^^^^^^^
lib/ui/app/forms/date_range_picker.dart:154:25: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                        ElevatedButton(
                        ^^^^^^^^^^^^^^
lib/ui/client/edit/client_edit_contacts.dart:92:18: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
          child: ElevatedButton(
                 ^^^^^^^^^^^^^^
lib/ui/client/edit/client_edit_contacts.dart:251:23: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                      ElevatedButton(
                      ^^^^^^^^^^^^^^
lib/ui/client/edit/client_edit_contacts.dart:266:23: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                      ElevatedButton(
                      ^^^^^^^^^^^^^^
lib/ui/task/edit/task_edit_times.dart:145:17: Error: 'ElevatedButton' is imported from both 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart' and 'package:flutter/src/material/elevated_button.dart'.
                ElevatedButton(
                ^^^^^^^^^^^^^^
lib/ui/task/edit/task_edit_times.dart:157:17: Error: 'ElevatedButton' is imported from both 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart' and 'package:flutter/src/material/elevated_button.dart'.
                ElevatedButton(
                ^^^^^^^^^^^^^^
lib/ui/vendor/edit/vendor_edit_contacts.dart:88:18: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
          child: ElevatedButton(
                 ^^^^^^^^^^^^^^
lib/ui/vendor/edit/vendor_edit_contacts.dart:239:23: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                      ElevatedButton(
                      ^^^^^^^^^^^^^^
lib/ui/vendor/edit/vendor_edit_contacts.dart:254:23: Error: 'ElevatedButton' is imported from both 'package:flutter/src/material/elevated_button.dart' and 'package:invoiceninja_flutter/ui/app/buttons/elevated_button.dart'.
                      ElevatedButton(
                      ^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\development\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\development\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hillelcoren** [comment]
Interesting... it looks like this file was recently added to Flutter master:

https://github.com/flutter/flutter/commits/master/packages/flutter/lib/src/material/elevated_button.dart

You may have more luck using the beta or dev channels

**Comment by jesulo** [comment]
I was lucky with beta, now app say Error: please check that invoice ninja v5 is installed on the server

**Comment by hillelcoren** [comment]
https://forum.invoiceninja.com/t/the-invoice-ninja-v5-beta-is-now-available/

**Comment by jesulo** [comment]
I have installed the branch v2, but when entering setup, I got error 500, then I reloaded the page and showed me the setup, configure the data but by accepting the terms and clicking next it gives me 500 error all the time,  An interesting fact is that in the setup page the view was very simple, not like in your video.  then use this command and migrated the database

php artisan migrate:fresh --seed && php artisan db:seed && php artisan ninja:create-test-data

Then website open.

But client web too show very simple, I think need some setting the setup Page and client page

![20200714_164301.jpg](https://user-images.githubusercontent.com/40969440/87475801-6591cc00-c5f3-11ea-8beb-60560d6e3648.jpg)

**Comment by hillelcoren** [comment]
Is it now working? There's a logout option on Settings > Device Settings.

**Comment by jesulo** [comment]
Now it works, I deleted the database and fill data in the setup again and this time it opened the dashboard for me.  I got some errors when I was using google chrome, 'token error 400 could not connect' when in configuration I gave it refresh the data.  'error no commands / model / companies' when I wanted to name the company.  after a while those mistakes stopped coming out.  But I noticed that both on the web and in the application the data is not updated correctly, for example create products and change the name of the company, from the google web, but they are not displayed in the android app, nor on the web  from internet explorer, although I gave it to refresh the page and configuration, it only updates when I closed and reopened session

**Comment by hillelcoren** [comment]
The apps auto-refresh every 15 minutes, you may just need to refresh the data to see it.

**Comment by jesulo** [comment]
I make refresh but really not working

**Comment by hillelcoren** [comment]
I'm not sure, are there any errors?

**Comment by jesulo** [comment]
Not errors, show like finish good but not refresh.

But I test now and working, maybe it was the caché
