### ISSUE TITLE
building error, master branch

### ISSUE THREAD

**Issue by jesulo** [invoiceninja/flutter-client#144]
hi, 

when run in android studio show this error.

event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in flutter-client-master...}
event sent after app closed: {id: 0, progressId: null, finished: true}
Launching lib\main.dart on SM G9650 in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\in_app_purchase-0.3.4+4\android\src\main\java\io\flutter\plugins\inapppurchase\MethodCallHandlerImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by hillelcoren** [comment]
Sorry, we don't currently support building the legacy branch

**Comment by jesulo** [comment]
Hi, this not is legacy, is master

**Comment by hillelcoren** [comment]
Those are warnings, not errors. Maybe the app just needs more time to start?

**Comment by jesulo** [comment]
It give me fail build,

event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in flutter-client-master...}
event sent after app closed: {id: 0, progressId: null, finished: true}
Launching lib\main.dart on SM G9650 in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\in_app_purchase-0.3.4+4\android\src\main\java\io\flutter\plugins\inapppurchase\MethodCallHandlerImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> Keystore file 'c:\Users\username\key.jks' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hillelcoren** [comment]
It looks like you've enabled code signing. 

Run `cp android/app/build.gradle.dev android/app/build.gradle` to support running the code unsigned.

**Comment by jesulo** [comment]
Yes working,

so for it to work in production I just have to sign the app.

There is another point, I understand that you do not support the previous version of the app, but in the new one there is no project and tasks module which is not related to budget, there is no option to import products.  This is why I still can't go to a new version.  Is there any way to compile the previous version without errors, thanks in advance

**Comment by hillelcoren** [comment]
Can you please explain how you're using the app, why are you compiling it rather than using the app from the app stores?

**Comment by jesulo** [comment]
I am wanting to add a module called Technical Service, which would work as Quote but is to present the tasks that have been done to the client

**Comment by hillelcoren** [comment]
Are you planning on selling it/do you understand the license? You wouldn't be able to remove the "Invoice Ninja" branding.

**Comment by jesulo** [comment]
no, I only want to use that function for my company, it would be very
useful not to make our sheet by hand

**Comment by hillelcoren** [comment]
We're working on porting the functionality, we hope to support tasks in v5 in the next few months.

**Comment by jesulo** [comment]
I understand, thank you

**Comment by jesulo** [comment]
Just for know your develop team not make customization like that, if yes please share email, thanks
