### ISSUE TITLE
building error, legacy branch

### ISSUE THREAD

**Issue by jesulo** [invoiceninja/flutter-client#145]
Hello,

I have this error when run in android studio,

event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in flutter-client-legacy...}
Because test_api >=0.2.19-nullsafety depends on boolean_selector >=2.1.0-nullsafety <2.1.0 and test >=1.3.0 <1.12.0 depends on boolean_selector ^1.0.0, test_api >=0.2.19-nullsafety is incompatible with test >=1.3.0 <1.12.0.
And because test >=1.12.0 depends on http ^0.12.0, if test_api >=0.2.19-nullsafety and test >=1.3.0 then http ^0.12.0.
And because every version of flutter_driver from sdk depends on test_api 0.2.19-nullsafety and invoiceninja_flutter depends on http ^0.11.3+17, test >=1.3.0 is incompatible with flutter_driver from sdk.
So, because invoiceninja_flutter depends on both flutter_driver any from sdk and test ^1.6.3, version solving failed.
event sent after app closed: {id: 0, progressId: null, finished: true}
pub get failed (1; So, because invoiceninja_flutter depends on both flutter_driver any from sdk and test ^1.6.3, version solving failed.)

**Comment by abedputra** [comment]
Have you fixed this issue?
