### ISSUE TITLE
Changing localization causes blank page (v5)

### ISSUE THREAD

**Issue by Codebreaker101** [invoiceninja/flutter-client#147]
As the title suggests, changing localization to anything other than English (1) causes blank page. Clearing cache and logging in again does not help. Only setting  `language_id` to 1 in database helps. There's nothing in the server logs and in the browser console (Chrome, Firefox). The only difference between the login response payload is `data[0]company.settings.language_id` key.

invocieninja c9be746583012051bd97b5844e017b2136af0152
php: 7.3.19-1~deb10u1
node: v12.18.3
npm: 6.14.6
composer: 1.10.10

**Comment by turbo124** [comment]
Are there any errors in storage/logs/laravel.log ?

**Comment by hillelcoren** [comment]
I've checked in a fix for this, when you get a chance please try again with the latest version.

**Comment by Codebreaker101** [comment]
Works like a charm!

**Comment by hillelcoren** [comment]
Awesome, thanks for the update!
