### ISSUE TITLE
self hosted login dashboard showing nothing except loader wheel

### ISSUE THREAD

**Issue by moiz212** [invoiceninja/flutter-client#151]
I have a self hosted url when I login into app I am getting like below image like result,
can you please help me I have server version 4.5.19 and flutter app latest master branch code something v5.0.13
<img width="518" alt="Screenshot 2020-09-03 at 5 17 27 PM" src="https://user-images.githubusercontent.com/51788555/92111335-c8d8f700-ee09-11ea-94b5-40ded60c0412.png">

**Comment by moiz212** [comment]
do I need to add any additional changes in code for self host login

**Comment by moiz212** [comment]
unable to run flutter pub get on legacy branch

**Comment by hillelcoren** [comment]
Hmm... I haven't used the legacy branch in the while, I think you'll need to use the app from the store

**Comment by moiz212** [comment]
do I need to update web app to v5 to use the client app

**Comment by moiz212** [comment]
or any changes I need to do for self host login

**Comment by hillelcoren** [comment]
There are two versions of the mobile app, the one in the store is for v4 whereas the beta mobile app is for v5.

**Comment by moiz212** [comment]
I am Able to connect with web app using App Store app

**Comment by moiz212** [comment]
so once I update web app to v5 will I able to connect and open dashboard.?

**Comment by hillelcoren** [comment]
The develop/master branches should work with the v5 app

**Comment by moiz212** [comment]
I will try after updating web app to v5 with develop/master branches code
Thank you so much for your kind help much appreciated ;-)
