### ISSUE TITLE
Sync InvoiceNinja client contacts with system contact database

### ISSUE THREAD

**Issue by skylarmt** [invoiceninja/flutter-client#152]
It would be great if this app could sync client contacts with the OS's native contact manager. That way I could call a contact without opening InvoiceNinja, searching for them, copying their number, and pasting it into the dialer app, as I must do currently. It would also mean that when clients call, they show up with their full name in the caller ID.
This is one of those quality of life things that IMO really puts the polish on an app.

**Comment by hillelcoren** [comment]
Thanks for the suggestion! Agreed, this would be very useful.
