### ISSUE TITLE
Unreadable font display

### ISSUE THREAD

**Issue by augnustin** [invoiceninja/flutter-client#153]
We just set up Invoice Ninja v5 :tada: 

Works great! Cool product. One thing bothers me though: 

With all font size adjustment effects, some appear clearly unreadable:

![image](https://user-images.githubusercontent.com/1970156/95478800-4d2f1480-098a-11eb-8e7a-824b22f8d754.png)

Anyone else having this issue? Any hint on the cause. I tried to inspect the DOM to look for some css `transform` property, but it's all `flutter` based. :(

Any hint on how to avoid this issue would be welcome!

Cheers

**Comment by augnustin** [comment]
Here's how it looks:

![image](https://user-images.githubusercontent.com/1970156/95721842-78a84c80-0c73-11eb-980d-acfceb914f07.png)

It does help then. Still looks a little blurry but much more readable for sure.

What surprises me is that my coworker, who has more or less the same environment (Linux + Chrome) did not have the issue.

Hope it helps. Not sure what's going on here.

Cheers

**Comment by augnustin** [comment]
And it looks much better on firefox:

![image](https://user-images.githubusercontent.com/1970156/95722310-0dab4580-0c74-11eb-8172-98a692db1d59.png)

**Comment by hillelcoren** [comment]
Thanks for the info, in the second picture did you enable or disable the code?

I think the problem is related to this issue, it may be connected to the screen's device pixel ratio

https://bugs.chromium.org/p/chromium/issues/detail?id=1040222

**Comment by augnustin** [comment]
On the firefox screenshot, I haven't changed anything, so the 

```
    flt-glass-pane {
        image-rendering: pixelated;
    }
```
is there. 

This may definitely be related to the issue you mentioned. Hence it shall be fixed at some point :crossed_fingers: 

I can use firefox by then.

**Comment by hmnd** [comment]
@hillelcoren I'm not particularly well-versed in Flutter, however setting window.devicePixelRatio to 2 fixes it for me on Chrome. Maybe that could be a viable temporary workaround?

**Comment by hillelcoren** [comment]
Thanks for the info, that's interesting! How are you setting the value?

The solution would make sense at it seems the bug only affects Chrome running on device pixel ratio 1.0 screens

https://github.com/flutter/flutter/issues/32274#issuecomment-572767237

**Comment by hmnd** [comment]
I just set it in my browser's console. So I think it would suffice to set that once at the beginning of every session.

**Comment by hillelcoren** [comment]
Thanks again, we'll look into it...

**Comment by hillelcoren** [comment]
Can you please check if the latest version helps?

**Comment by hmnd** [comment]
@hillelcoren I actually just checked a few days ago and it does!  Thank you very much :)

**Comment by hillelcoren** [comment]
Awesome, glad to hear it!
