### ISSUE TITLE
"Take Picture" causes IN to crash iOS

### ISSUE THREAD

**Issue by NPCtom** [invoiceninja/flutter-client#161]
Using the "Take Picture" function under the documents tab on an invoice causes the app to close.

iPhone 11 Pro iOS 14.2

**Comment by hillelcoren** [comment]
Hi,

Can you check the app has permission to use the camera?

**Comment by NPCtom** [comment]
Thank you for your prompt reply.
Invoice Ninja has access to All Photos. No camera permission is visible in the corresponding window in the iOS Settings app.
Can you reproduce this on public beta iOS 14.2?

**Comment by hillelcoren** [comment]
Thanks, I can reproduce this.

We'll work on a fix...

**Comment by hillelcoren** [comment]
I've checked in a fix for this
