### ISSUE TITLE
Various v5 Issues

### ISSUE THREAD

**Issue by srichter** [invoiceninja/flutter-client#165]
These are the various issues I've found in v5 (using v5-stable branch, on commit 792262dee44380209869392d0f0fd19f7e78cbb3) so far. I can open PRs to fix these if desired:

1. `app/Http/Requests/Project/UpdateProjectRequest.php:36` Missing import of `Illuminate\Validation\Rule`

2. `app/Http/Controllers/SetupController.php:176` This attempts to `count($response_array)`, but if an exception is caught in `SystemHealth::testMailServer()` it will return the exception message as a string and the count will cause a warning.

I don't have a Flutter development environment set up, so I can't fully debug these, but on the frontend:

1. I'm not sure if it's just not implemented yet, but selecting the "Task" report causes the entire reports UI to break and throw a constant error in the console. I had to remove `reportsUIState` from `flutter.ui_state` in local storage to fix the page.

2. When you select a Time entry inside of a Task and the modal for entering date/start/end/duration pops up, if you select "Done" without modifying anything, it will advance the date of the Time entry by 1 day each time. My date format in settings is `Jan 31, 2000`.

**Comment by turbo124** [comment]
@srichter thanks for updating, i've moved this into the flutter issues for further discussion.

**Comment by hillelcoren** [comment]
I'm no longer able to reproduce the issue, to confirm we're testing with the same code I've checked in a new build (v28).  When you get a chance can you please see if it helps.

**Comment by srichter** [comment]
I can't reproduce it on v28 either

**Comment by hillelcoren** [comment]
Great to hear, thanks for the update!
