### ISSUE TITLE
FEATURE REQUEST: Make version number in about model selectable

### ISSUE THREAD

**Issue by jonathannz** [invoiceninja/flutter-client#166]
Would it be possible to make the version number in the About modal selectable? So that one can select and copy the version number? 

Or even better, make it clickable, such that clicking it automatically copies it to clipboard. This would make it easier to report bugs.

**Comment by hillelcoren** [comment]
Thanks for the suggestion, I've made the version clickable to copy it.

It will be included in the next release.
