### ISSUE TITLE
After update to 5.0.34-28, the SAVE and CANCEL buttons have disappeared

### ISSUE THREAD

**Issue by jonathannz** [invoiceninja/flutter-client#167]
Today I updated from 5.0.31 to 5.0.34, and I see that buttons for saving and cancelling actions (invoices, recurring invoices, settings, etc.) have vanished. 

They are there, but styled such that they are invisible.

This image shows where they are:
![image](https://user-images.githubusercontent.com/667395/101719424-2adf8180-3b08-11eb-9109-bf6ae3b10f69.png)

This image shows how they appear when hovered over:
![image](https://user-images.githubusercontent.com/667395/101719561-6ed28680-3b08-11eb-9358-2705f8cbb61f.png)

They can be faintly seen.

**Comment by hillelcoren** [comment]
Thanks for reporting this! I'm having trouble reproducing the issue.

It may help to set an accent color on Settings > User Details but I'd like to figure out why it isn't working...

**Comment by hillelcoren** [comment]
Do you see the same problem using the demo?

https://demo.invoiceninja.com

**Comment by jonathannz** [comment]
The demo has a dark theme applied, and the buttons show up as expected.

**Comment by jonathannz** [comment]
And when I switch it to non-dark mode, I can see the Cancel and Save buttons as black text (no actual button around it, but the text is visible).

![image](https://user-images.githubusercontent.com/667395/101732384-01335400-3b22-11eb-8d2b-c8548f494baa.png)

**Comment by jonathannz** [comment]
I've switched my installation to Dark Mode, and I can see the Cancel and Save text.

And, interestingly, when I switch off Dark Mode, I can now see the buttons in light mode too!

**Comment by hillelcoren** [comment]
Thanks, that's helpful to know
