### ISSUE TITLE
Custom fields on invoices are not populated when editing an invoice

### ISSUE THREAD

**Issue by jonathannz** [invoiceninja/flutter-client#168]
Version 5.0.34-28

Situation:

I have a few custom fields on invoices.
When I enter a value into the custom field, and save the invoice, I can see the field data in the invoice preview panel on right.

But when I edit the invoice, the field is blank.

If I save it again, the data I originally entered into that field still shows up in the invoice preview.

Seems like a bug.

**Comment by jonathannz** [comment]
Just a regular custom field... under Products

![image](https://user-images.githubusercontent.com/667395/101750233-9d198b80-3b33-11eb-9d1c-52c76484ab58.png)

Shows up here on Invoices ...

![image](https://user-images.githubusercontent.com/667395/101750328-b91d2d00-3b33-11eb-9b88-1744b829335d.png)

**Comment by hillelcoren** [comment]
Thanks, that helps! I thought you meant custom invoice fields. 

I'll look into it...

**Comment by hillelcoren** [comment]
I'm able to reproduce the problem and have checked in a fix
