### ISSUE TITLE
InvoiceNinja-App shows only grey

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/flutter-client#169]
![Screenshot_20201205-070912](https://user-images.githubusercontent.com/28981528/101751008-0ebfee00-3ad0-11eb-8372-7ce8a52978e4.jpg)
After logging in, the app only shows grey

**Comment by hillelcoren** [comment]
Hi,

Is the dashboard loading correctly in the web app?

**Comment by LarsK1** [comment]
Yes, it is
![image](https://user-images.githubusercontent.com/28981528/101752047-51ce9100-3ad1-11eb-8767-34378d8fe631.png)

**Comment by hillelcoren** [comment]
Ok, thanks! Error logging isn't currently enabled in the mobile app but will be adding the next release in a few days, it should help track down the problem.

**Comment by hillelcoren** [comment]
You may want to check if changing the app language to English helps

**Comment by LarsK1** [comment]
Nope, still all grey

**Comment by hillelcoren** [comment]
Ok, thanks for trying! If you have error reporting enabled in the .env file we should see it with the next release

**Comment by LarsK1** [comment]
Error reporting is enabled. Can you inform me, when implemented?

**Comment by hillelcoren** [comment]
Note: it looks like you have debug mode enabled, if the app is publicly accessible we strongly recommend disabling it as it can leak secure credentials

**Comment by LarsK1** [comment]
Thanks for the hint - disabled it for now.

**Comment by LarsK1** [comment]
@hillelcoren any news?

**Comment by hillelcoren** [comment]
Have you had a chance to try with the latest version of the mobile app?

**Comment by LarsK1** [comment]
Installed the latest version available in the Google PlayStore still no changes from image above

**Comment by hillelcoren** [comment]
Which version of the Android app are you using?

**Comment by LarsK1** [comment]
v5.0.30

**Comment by hillelcoren** [comment]
I'm not sure, can you check if deleting and then reinstalling the app helps?

**Comment by Akjo4712** [comment]
I am also seeing just a grey screen on my iPhone with the latest App from Testflight (v5.0.30).

**Comment by hillelcoren** [comment]
Do you have error reporting enabled in the .env file? 

If you slide from the left do you see the menu drawer?

**Comment by Akjo4712** [comment]
No action does change the gray screen, i tried swiping, pinch to zoom and any other common gesture for touch interaction. But the last time the Application was updated i saw the UI, until i changed from my Test Company to my Production Company. After that, the screen was all over gray again.

**Comment by hillelcoren** [comment]
Have you tried deleting and then reinstalling the app?

**Comment by LarsK1** [comment]
Now the apps keeps crashing even befor I can enter any data into the login formular. (after reinstalling)

**Comment by hillelcoren** [comment]
Thanks, I'll check the logs...

**Comment by Akjo4712** [comment]
Just reinstalled the App. Still a gray screen after login.
I am using the Docker Version of Invoice Ninja. APP_DEBUG=true is set as Environment Var.

**Comment by hillelcoren** [comment]
Does changing APP_DEBUG to false make a difference? After changing the .env file you may need to run php artisan optimize

**Comment by Akjo4712** [comment]
Just made an Update to Invoice Ninja Server, but now i am unable to start the server. Getting a lot of "chown ... Operation not permitted" Errors.

Definitly not related to this Issue. Shall i create a new Issue for that one?

**Comment by hillelcoren** [comment]
Thanks, that would be helpful

**Comment by LarsK1** [comment]
Seems like the crash is caused by android autofill

**Comment by hillelcoren** [comment]
Thanks for the info! Are you able to send any error details?

**Comment by LarsK1** [comment]
Not really, just the information that when I disable Roboform (my password manager) in the android autofill settings, i can login, but can only see grey.

**Comment by hillelcoren** [comment]
Thanks for the info, we're working on a new version of the mobile app with more logging....

**Comment by hillelcoren** [comment]
We've just deployed a new release, it will likely still fail but should log errors (if error reporting is enabled).

**Comment by LarsK1** [comment]
Still the app crashes instantly - see [this Video](https://gmgbt-my.sharepoint.com/:v:/g/personal/lars_kusch_gmg-bayreuth_net/EdxhlbmdNRlIq2fdoNYMszwBHtPzQfZtIrLmaweoFhDHqw?e=5a6XLu)

**Comment by hillelcoren** [comment]
Thanks for the video, that's helpful!

Can you please try disabling your password manager again.

**Comment by hillelcoren** [comment]
I think I may see the problem, it seems likely it's related to this issue:

https://github.com/flutter/flutter/issues/72185

We'll include a suggested fix with the next release.

**Comment by LarsK1** [comment]
Disabled the password manager, the issue still appears: [Video](https://gmgbt-my.sharepoint.com/:v:/g/personal/lars_kusch_gmg-bayreuth_net/EXr5nfzq0MdBjeJiM3e_jIgBIaoDtKI5ThOM87EpLHpZ_Q?e=rrKE00)

**Comment by hillelcoren** [comment]
I think this is a new issue introduced in the last release by changes made to correct error tracking. 

Thanks for your patience, we'll get there eventually...

**Comment by hillelcoren** [comment]
New version is live...

**Comment by LarsK1** [comment]
I'm sorry - but the issue still persists. App's crashing as soon as tapping on any text-entry-box

P.S. merry Christmas 🎄

**Comment by hillelcoren** [comment]
Which version of Android are you using?

To you too :)

**Comment by hillelcoren** [comment]
I was using Android 9, once I updated to Android 11 I've started seeing the same error. 

We've deployed a new build (v35) with a fix, you should hopefully be able to login but will most likely still see the grey screen.

**Comment by LarsK1** [comment]
11, RQ1A.201205.008

**Comment by LarsK1** [comment]
Can enter now, but the following error appears:
`Error :: '[{id: 4, capital: Kabul, citizenship: Afghan, country_code: 004, currency: af...' to 'BuiltList<CountryEntity>' failed due to: Deserializing '[id, 4, capital, Kabul, citizenship, Afghan, country_code, 004, currency, afg...' to 'CountryEntity' failed due to: Tried to construct class "CountryEntity" with null field "thousandSeparator". This is forbidden; to allow it, mark "thousandSeparator" with @nullable.`

**Comment by hillelcoren** [comment]
Nice, progress :) 

Can you check you're using the latest web version, we shared a new release recently.

**Comment by LarsK1** [comment]
Updated to the latest dev-version no change at all. Maybe related to #4558, php artisan migrate changed nothing 🤔

**Comment by LarsK1** [comment]
Now being able to login - still grey. Will append the logs tommorow

**Comment by LarsK1** [comment]
@hillelcoren ?

**Comment by hillelcoren** [comment]
We'll have a new mobile release soon

**Comment by hillelcoren** [comment]
I've looked into this further, as mentioned earlier on https://github.com/invoiceninja/flutter-client/issues/169#issuecomment-742395005 I think this is a language problem. I suggest testing with English as the language again, assuming this is the problem we'll include a fix with the next release.

**Comment by Akjo4712** [comment]
Can confirm, after changing to English and reinstalling the App everything works fine.

**Comment by hillelcoren** [comment]
Great, we'll deploy a new release with a fix

**Comment by LarsK1** [comment]
Yey, you made it! Thanks for the fix!
