### ISSUE TITLE
Field order is not draggable in Product Columns on Invoice design

### ISSUE THREAD

**Issue by jonathannz** [invoiceninja/flutter-client#171]
Version:  5.0.34-26

In the Product Columns (in Invoice Design) I presume the fields are meant to be draggable, so you can change their order.

Currently they don't seem to be.

![image](https://user-images.githubusercontent.com/667395/101880910-88eb9200-3bf8-11eb-9baa-c6f5c350c04f.png)

My expectation is the little four bar hamburger means I can drag to change order.

**Comment by hillelcoren** [comment]
FYI.. we've just updated the macOS desktop build, it should resolve some of your outstanding issues.

http://download.invoiceninja.com/macos

We'll have a new web build soon. Thanks again for all of the feedback!
