### ISSUE TITLE
Can't edit Invoice when Mode is "Assign Invoice Number on send" with Error "Please enter Invoice Number"

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#173]
Hello!

I recently changed from "Assign Invoice Number on Save" to "Assign Invoice Number on Send". This leads to an error when editing an Invoice, which still has no Invoice Number. 

When I try to save my changes, i get a Error Message, which says "Please enter Invoice Number".
![image](https://user-images.githubusercontent.com/65533611/102488774-df2f5980-406c-11eb-8f45-8eaf98f50013.png)

By my understanding, I should be able to make changes to not sent Invoices. But this field seems to be a required Field, but as the numbers are only generated when sending the Invoice I can't make any changes.

If you need any further information, feel free to reach out to me.

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be resolved in the next release

**Comment by Akjo4712** [comment]
Nice to hear! Thank you.
