### ISSUE TITLE
Euro Sign is randomly left or right in the Client Table

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#174]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.0.44-C37

**What environment are you running?
Docker

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
When i view the Client overview, the Euro Sign is sometimes left and sometimes right. In my opinion this should be either left or right for all values in Euro.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/104004553-21e3dd80-51a4-11eb-88c0-755a56d03dfd.png)

**Comment by hillelcoren** [comment]
Thanks for reporting this!

The behavior is by design but it's definitely possible the design is wrong. The location of the currency symbol is determined by the client's currency and country. maybe the admin portal should be changed to match the user's settings instead.

**Comment by Akjo4712** [comment]
Your idea sounds correct. I would expect the symbols and amounts to line up in a Table View. So Admin Portal should follow User Setting, Invoices and Client Portal should follow Client Settings.
