### ISSUE TITLE
Multi-currencies management

### ISSUE THREAD

**Issue by rodrigofarcas** [invoiceninja/flutter-client#175]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?

Docker

**Have you searched existing issues/requests?**

Yes

**Screenshots**
If applicable, add screenshots to help explain your request/question.

My main currency is USD
![](https://forum.invoiceninja.com/uploads/default/original/2X/a/ade30862bcfd2985b4440dae84855f24d8853118.png)

I did an invoice in CLP$ adding the Exchange Rate to $730, meaning 1 USD = $730 CLP
![](https://forum.invoiceninja.com/uploads/default/original/2X/9/99c4c563d51c7d27f9e199ab911e6c49563df345.png)

My expected behavior would be to see all other areas in the app, showing numbers converted to USD, as it is my main company currency. Ideally showing local (CLP) and converted to USD amounts.

![](https://forum.invoiceninja.com/uploads/default/original/2X/9/99c4c563d51c7d27f9e199ab911e6c49563df345.png)

Then finally, we can do this, 2 clients, in 2 different countries, with different currencies, shown in USD in reports, so you know how much the company as a whole is selling

![](https://forum.invoiceninja.com/uploads/default/original/2X/d/d866f21cfdbd35c82529cf811c91ad50967d705f.png)

**Additional context**

- We have 2 branches, one in Chilean pesos (CLP) and one in Mexican pesos (MXN).
- I know I can setup default currency per client.
- Now, we have set USD as our main currency on "Settings - Localization" so reports are shown in a third currency, which should be USD$ for a consolidated view.
- This is very useful for businesses with multiple countries operations, were the common currency for reports can be USD
- This mean, you can use the invoicing system to use it with all local branches the company has, with different currencies but with high value reports were you can see everything normalized as the “big” numbers of the company.

**Comment by hillelcoren** [comment]
Hi,

We'll consider it for the future. 

FYI.. the dashboard should already support this.

**Comment by hillelcoren** [comment]
In the next version of the app we've added convert amount/balance columns to support this.

Thanks for the suggestion!

**Comment by rodrigofarcas** [comment]
Great!  I will try it and give feedback once a build is available to test this.

**Comment by rodrigofarcas** [comment]
Hello @hillelcoren is this available already on the development branch? asking because we've updated and could not find it to give it a look.

Thank you

**Comment by hillelcoren** [comment]
Not sure, there should be new 'converted' optional columns available

**Comment by rodrigofarcas** [comment]
Hello @hillelcoren I am running now v5.0.43-C41 but there is no such column to add to reports https://prnt.sc/yd9z45

**Comment by hillelcoren** [comment]
We added the fields to the invoice report as which was reported above, I'll look into also adding the fields to the client report

**Comment by rodrigofarcas** [comment]
Great! Would be nice to have this column everywhere you want to use it basically, and probably a global setting to show it.

Just to share some insights, been playing with Zoho Invoice.

You setup allowed currencies https://prnt.sc/ydb8wh
you set client currency (as you do) https://prnt.sc/ydbd8z
invoice is local currency https://prnt.sc/ydbhc5
when you do a new invoice, it prompts a conversion suggestion https://prnt.sc/ydbltd
all reports show with my default currency which is usd (same we can achieve with conversion column) https://prnt.sc/ydbqri

Hope it adds value. Thanks.

**Comment by hillelcoren** [comment]
Thanks, that's very useful to see!

FYI.. some of this is already support in v5, here are some tips:

- To define a list of available currencies you could create a group for each currency and then select the group when creating the client. This would set the client's currency and enable you to define currency specific settings. 

- You can enable 'Convert Products' on Settings > Products to have the app auto-convert the amounts, the exchange rate is tracked on the edit invoice page on the settings tab.
