### ISSUE TITLE
Selfhost - Localization not applied to emails

### ISSUE THREAD

**Issue by yannickboy15** [invoiceninja/flutter-client#178]
When creating an invoice or quote (Haven't tried the others) and you send it by email over the app, you'll notice that the email is not translated/adjusted to the format you've given it while editing this in the settings. I've got my localization set to Dutch and I've received the email in English. The whole app is in dutch though. Below a screenshot.

The mail sent from my test environment. As you can see the button is translated, the text isn't while this works fine on browser.
![20210116_123508](https://user-images.githubusercontent.com/20385056/104810789-60f2de00-57f7-11eb-8a63-dc1110ef8729.jpg)

The app on my test environment
![Screenshot_20210116-123333](https://user-images.githubusercontent.com/20385056/104810750-14a79e00-57f7-11eb-9b13-68a0378eb45b.jpg)

**Comment by hillelcoren** [comment]
Hi,

It looks like you're using v4, this should be resolved in v5.

https://invoiceninja.github.io/selfhost.html
