### ISSUE TITLE
Missing Translation for German

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#179]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.0.50-C38

**What environment are you running?**
Docker

**Describe the bug**
Some tranlsations are missing. See Screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/105047675-e8945300-5a6a-11eb-8ae0-eaef558022ea.png)
![image](https://user-images.githubusercontent.com/65533611/105047838-1f6a6900-5a6b-11eb-989e-b1e3db6d6ef3.png)

**Comment by hillelcoren** [comment]
This is fixed in the next release
