### ISSUE TITLE
Expenses by category report missing

### ISSUE THREAD

**Issue by cmolnar65** [invoiceninja/flutter-client#182]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**

5.0.56-C40

**What environment are you running?**

ZIP
Ubuntu

**Have you checked log files (storage/logs/) Please provide redacted output**
Not Applicable

**Have you searched existing issues?**

Yes

**Have you reported this to Slack/forum before posting?**

No

**Describe the bug**

In V4 we could report expenses by category. This is a MAJOR requirement for tax purposes. This seems to be missing from the report --> Expense  dropdown.

**Steps To Reproduce**
Report --> Expenses

**Expected behavior**
Show report of current years expenses by category

**Comment by hillelcoren** [comment]
We've added support for this in the next version

**Comment by cmolnar65** [comment]
Thanks. I did receive in in this morning's v5-develop update. It works great.

**Comment by hillelcoren** [comment]
Glad to hear it, thanks for the update!
