### ISSUE TITLE
New task created within a Project's Task List should automatically have Client and Project pre-filled

### ISSUE THREAD

**Issue by tmlmt** [invoiceninja/flutter-client#183]
**What version of Invoice Ninja are you running?
v5.0.56

**What environment are you running?**
Self-hosted, installed with git

**Have you checked log files (storage/logs/) Please provide redacted output**
Yes. No relevant logs

**Have you searched existing issues?**
Yes. Nothing relevant found when searching for term "task"

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
Project's details are not filled in when creating a new task within a Project's Task List

**Steps To Reproduce**
- Projects > Select a Project
- Click on Tasks to make list of tasks appear
- Click on "+" to create a new task

**Expected behavior**
As we're creating a new task from within a Project's Task List, the Client and Project are known and should be pre-filled. I believe it's a bug because the New Task shows up as a complete blank new task

**Screenshots**
![image](https://user-images.githubusercontent.com/10244927/106672213-fe982c80-65af-11eb-9536-2f4ec96d8adb.png)
![image](https://user-images.githubusercontent.com/10244927/106672302-225b7280-65b0-11eb-9809-15c3056fa2fa.png)

**Comment by hillelcoren** [comment]
Thanks for reporting this, it's fixed in the next release.
