### ISSUE TITLE
Keep pagination and open tab after viewing pdf

### ISSUE THREAD

**Issue by gijsrutten** [invoiceninja/flutter-client#184]
Hi,

Not realy an issue but maybe something that can be “fixed” someday.

When I browse through the pages of invoices etc. and click _View PDF_ and then again _close_ the preview again, it will go back to page 1 and doesn’t stay on the page that was open before I viewed the pdf.

Also on the details pane at the right side, it will open the overview again although I was on a different tab before.

Nothing really bad but maybe worth to look at.

Many thanks in advance!
Gijs

https://user-images.githubusercontent.com/26574517/107223620-b09f8080-6a16-11eb-9d42-d99fadaeaad2.mov

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this, 100% agreed. 

I've checked in a new build of the admin portal to v5-develop branch, it will be included with the next release.
