### ISSUE TITLE
Can't start Recurring Invoice duplicated from Invoice

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#186]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.5-C41

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
No, have not checked, currently not in Office and no access to logs

**Have you searched existing issues?**
Yes, there is another Issue regarding Starting Recurring Incoves, but I don't think it is related.

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
I copied a Inoivce to Recurring Invoice. Now I am unable to start the Recurring Invoic. When i hit Start, i get a Message with "Started" but i always see, that the Recurring Invoice is in state Draft.

**Steps To Reproduce**
Create Invoice, while the Invoice is in Draft, copy it to Recurring Invoice, try to Start Recurring Invoice, state keeps draft.

**Expected behavior**
When hitting the Start Button, the Recurring Incoice should change its status.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/107637689-d3c46d00-6c6e-11eb-8307-ae138c6fb9f7.png)

**Comment by turbo124** [comment]
@hillelcoren endless should be default?

**Comment by hillelcoren** [comment]
Probably a bug caused by cloning, I think I can fix it in the AP
