### ISSUE TITLE
Deleted Time Tracking Entries are added to Invoice

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#187]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.5-C41

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
No

**Have you searched existing issues?**
No

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
When creating a Invoice from a Project, Time Tracking Entries which are deleted are also added to the Invoice.

**Expected behavior**
Deleted Time Tracking Entries should not be added to Invoices.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/107854358-9b15c680-6e1b-11eb-90ba-9f3d4c93bc45.png)
![image](https://user-images.githubusercontent.com/65533611/107854399-c7c9de00-6e1b-11eb-96de-bb797e9767c0.png)
![image](https://user-images.githubusercontent.com/65533611/107854436-0fe90080-6e1c-11eb-9456-26c7e9cdc0f6.png)

**Comment by hillelcoren** [comment]
Thank you finding all of these issues, you're awesome!
