### ISSUE TITLE
Can't click on Button in Pop Up while PDF is in Background

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#188]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.5-C41

**What environment are you running?**
Docker

**Describe the bug**
While the Invoice PDF is in Background i can't click on any Button in the Pop Up. As there is no way to exit the Pop Up other than the close Button, you have to reload the Page.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/107854536-bb925080-6e1c-11eb-8860-5ff7b1cf5746.png)

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this, we'll look into it.

**Comment by hillelcoren** [comment]
I don't currently have a good way to properly fix this. 

For now I'm going to disable the about button on this screen to prevent the app from getting into an invalid state. 

Hopefully in the future we're able to provide a better solution but I think this is ok for now.

**Comment by Akjo4712** [comment]
@hillelcoren, the Problem might be more wide than thought. Just noticed that sending Invoices also has an Embed PDF, the Error Message i got can't be dismissed with the Button. I can only close by clicking outside the Pop Up to the Left, where the PDF is not located.

![image](https://user-images.githubusercontent.com/65533611/109263780-23c13900-7804-11eb-8436-d4d7cac6706d.png)

I think if Invoice Ninja develops and might use more Pop Up Dialoges sometimes, this Problem might get more and more relevant, as disabling dialogs on those Views might not be possible, as by your fix above.

Just wanted to inform you about my concerns, your decission how to handle this. As my current sample is "just" a error message, nothing which should happen daily, this isn't a big thing currently.

**Comment by hillelcoren** [comment]
Hi,

If this error is reproducible can you please create a new issue issue with the details from the error log.

**Comment by Akjo4712** [comment]
Already done so. https://github.com/invoiceninja/invoiceninja/issues/4995

**Comment by hillelcoren** [comment]
Brilliant, thanks!

I don't think we'll be able to fix the problem with the popup, it's caused by the framework we're using so it outside our scope of control.

**Comment by Akjo4712** [comment]
Okay, I understand.
