### ISSUE TITLE
Uploading a Document to a Invoice removes all assosiated Articles in the Invoice

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#189]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.5-C41

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
Yes, nothing to see.

**Have you searched existing issues?**
No

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
When i attach a File to Invoice, all Line items are removed.

**Steps To Reproduce**
Create invocie, enter some line items, attach a document, all line items are lost

**Expected behavior**
When adding a document, no data should be deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/107737092-e472f280-6d03-11eb-9e3a-505af7530af1.png)

**Additional context**
Same Issue with Invoices in Draft mode.

**Comment by hillelcoren** [comment]
Thanks for catching this serious issue, it should be resolved in the next version.
