### ISSUE TITLE
User Flow for creating additional Users is not clear

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#191]
I created a Account for a Co-Worker. As there was no way to set a Password in the UI, I first thought of a Bug. The Password Field was there some Versions ago. My Co-Work just informed me that he was able to login, this now revealed that there was an email sent to him.

Afterwards, the process is clear and straight forward. But the first time use was a little adventure for me.
If ther was a Pop-Up after saving, that a Mail was sent to [Address], this would have been clear to me.

**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.1.5-C41

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
Yes

**Comment by hillelcoren** [comment]
Thank you for reporting this!

In the next version you'll see a message saying an email has been sent.
