### ISSUE TITLE
$company.custom values 

### ISSUE THREAD

**Issue by BeefoIO** [invoiceninja/flutter-client#199]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.10-C43

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
no need

**Have you searched existing issues?**
yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
In the Invoice-Template it tells you to use `$company.custom1` but its actually `$company1`

**Steps To Reproduce**
Edit Invoice-Template

**Expected behavior**
The custom values should be available at `$company.custom1`

**Comment by hillelcoren** [comment]
I'll update the admin portal to match
