### ISSUE TITLE
Overlap of Design with modal dialog and PDF Viewer.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [invoiceninja/flutter-client#201]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.14-C44

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
No

**Have you searched existing issues?**
No

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
Some kind of overlap issue can't click Close on System Health model when New Design with preview is open.

**Steps To Reproduce**
Note: Screen resolution to reproduce in Google Chrome with responsive, but happens on other resolutions too.
1280x1024

1) Click Settings
2) Click Invoice Design
3) Click Customize & Preview
4) Click the i Info Icon in bottom left.
5) Click Health Check
6) Click on right side of Close button.

**Expected behavior**
No z-index/overlap issue should be present.

**Screenshots**
Google Chrome
![image](https://user-images.githubusercontent.com/1968109/109947944-bbf87a00-7d3e-11eb-8b9b-d1b6f0e99ecc.png)

If I right click and inspect it, I am looking at the view thumbnails element.

![image](https://user-images.githubusercontent.com/1968109/109946560-3c1de000-7d3d-11eb-87e7-adff9f1c92d1.png)

**Additional context**
Z index issue with modal and pdf viewer? (Possibly other areas)

**Comment by hillelcoren** [comment]
Thanks for reporting this! The underlying problem is caused by the framework we're using which we won't be able to fix ourselves however as a workaround we can hide the about icon on pages containing the PDF.

**Comment by LiamKarlMitchell** [comment]
Ah sorry, I was not aware of the flutter-client repo. I'll try to remember to post UI experience issues here if I see them :)
Thanks.

**Comment by hillelcoren** [comment]
FYI.. we've found this package which fixes this:

https://pub.dev/packages/pointer_interceptor

This should be resolved in the next version
