### ISSUE TITLE
Take over of Invoice Adress to Delivery Adress doesn't take over Country

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#202]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.14-C44

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
No

**Have you searched existing issues?**
No

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
When i hit the Copy Adress Button all information shows up, except the Country which i have choosen in the other Tab.

**Expected behavior**
Along with all Text Values, also the Country should be copied.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/109946998-24147500-7cd9-11eb-95b9-9f8a911cb28d.png)

**Comment by hillelcoren** [comment]
Thanks for catching this!
