### ISSUE TITLE
Unticking "Vendors" doesn't work & missing label

### ISSUE THREAD

**Issue by beganovich** [invoiceninja/flutter-client#204]
Issue no. 1: Unticking Vendors from Enabled modules, doesn't do anything. (ref: https://forum.invoiceninja.com/t/cant-remove-vendors-module/6127)

Issue no. 2:
![image](https://user-images.githubusercontent.com/13711415/109966357-7745f200-7cf0-11eb-902a-c40f25c45c48.png)

**Comment by hillelcoren** [comment]
Thanks! I'll look into it...
