### ISSUE TITLE
403 invalid secret on ios app 

### ISSUE THREAD

**Issue by jdetmold** [invoiceninja/flutter-client#205]
What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30
5.1.14 

What environment are you running?
Self Hosting

I have set API_SECRET= in the .env and can sign in with this on my desktop in chrome but using it in the ios app I always get 403 invalid secret.
the secret is correct i can copy and pate it to the ios app and it errors if i paste the same secret to the web browser in ios it works

**Comment by hillelcoren** [comment]
Can you confirm you're using the v5 iOS app

https://testflight.apple.com/join/MJ6WpaXh
