### ISSUE TITLE
Function to reorder Invoice Items and Quote Items

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#208]
Like seen in some other screens in Invoice Ninja, i currently don't remeber where, i would like to see the possibility to easily reorder the Items on Invoices and Quotes. I sometimes need this while making Quotes, as i don't exactly know how it will look in the end. Currently reorder of Items means lot's of Copy and Paste work which is error-prone.

**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.1.14-C44

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
No

**Comment by gowallasnewpony** [comment]
oh yeah, me to! please add this enhancement!

**Comment by hillelcoren** [comment]
I'd like to support dragging/dropping the rows as we do in v5 but it isn't currently supported by the UI toolkit we're using, I've tried a package but it didn't work well.

Failing that... we've changed the clear icon to a dropdown with options to move the item.

**Comment by hillelcoren** [comment]
![image](https://user-images.githubusercontent.com/4629496/114416283-3081cc80-9bb9-11eb-8dc3-de6711ddc233.png)
