### ISSUE TITLE
Fingerprint auth cant be enabled

### ISSUE THREAD

**Issue by tixsys** [invoiceninja/flutter-client#209]

**Comment by hillelcoren** [comment]
Hi,

What device are you using?

**Comment by tixsys** [comment]
Samsung note 10 plus. Android 9

**Comment by hillelcoren** [comment]
Thanks, and which version of the app?

**Comment by tixsys** [comment]
5.0.14

**Comment by hillelcoren** [comment]
That's the web app version, can you please send the mobile app version you're using?
