### ISSUE TITLE
Empty header on Invoice template causes fatal error

### ISSUE THREAD

**Issue by bugzbrown** [invoiceninja/flutter-client#212]
If you customize an invoice template an remove the header div from the header section leaving it empty, the system will warn you about a null key and crash.
After that happens, you are not able to log into the system anymore because of this null value
(at least it's what I did to get the error) 
- From the error message - it would look like it's something to do with the company logo (my company does not have one registered)

This is what I managed to salvage from the error
```
Error :: '[id, gl9avmeG1v, name, GregoryBrown, is_custom, true, is_active, true, design...' to 'minified:cR' failed due to: Deserializing '[body, <div id="body">
    <div class="company-logo-wrapper">
        <img cl...' to 'minified:D<String, String>' failed due to: Invalid argument(s): null key

```

**Comment by hillelcoren** [comment]
Thanks for reporting this!

@turbo124, I think the API may be converting the empty string to null?

**Comment by bugzbrown** [comment]
It looks like my guess was right about the problem being with the header field... 
I just checked out the data in the DB and header was set to null

This is the output of the field **design** in the **designs** table:
```
{
  "header": null,
  "body": "<div id=\"body\">\n    <div class ...[ Snipped for brevity ]...</table>\n</div>",
  "footer": "<div id=\"footer\"></div>",
  "product": "",
  "task": "",
  "includes": "<style id=\"style\">\n    ...[ Snipped for brevity ]... padding-right: 0.5rem;\n    }\n</style>"
}
```
Setting **header** to `<div></div>`  solved the issue and I am able to login again.
I´ll try and have a look after work at what may be causing it, but at least there is a fairly simple work around for whomever might get in trouble.

**Comment by hillelcoren** [comment]
I believe this middleware automatically converts all empty strings to null which causes problems here:

https://github.com/invoiceninja/invoiceninja/blob/v5-develop/app/Http/Kernel.php#L70

**Comment by turbo124** [comment]
fixed here

https://github.com/invoiceninja/invoiceninja/pull/5094
