### ISSUE TITLE
Quick add products when creating Quote/Invoice

### ISSUE THREAD

**Issue by Waaiez** [invoiceninja/flutter-client#213]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
4.5, planning to upgrade to v5 once it arrives on Softaculous so this is a feature request for v5

**What environment are you running?**
Shared Hosting

**Have you searched existing issues/requests?**
Yes, similar to invoiceninja/invoiceninja#2713

**Screenshots**
If applicable, add screenshots to help explain your request/question.
![feature-request](https://user-images.githubusercontent.com/43832467/111063384-db1da700-84b6-11eb-9765-b7e0e4668c40.png)

**Additional context**
Add any other context about the request/question here.
Before moving to Invoice Ninja we used Sage Accounting and it had a useful feature to quick add items without leaving the current quote you were working on and you didn't need to refresh the page for the new product to show up in the list.
This could be functionally similar to how you can currently quick add customers
![feature-request2](https://user-images.githubusercontent.com/43832467/111063497-80d11600-84b7-11eb-9676-3fceb403f5c6.png)

You can take a look at the [Sage Accounting Demo](https://accounting.sageone.co.za/landing/demologin.aspx) to get a feel for how it worked there, but it was basically just selecting 'Add item' and it brought up popup where we could add all the relevant information and then click save and it would appear in the list of items.
To get open the open link, hover over customers, go down to transactions then click customer quotes. Then click add quote and then click 'select item' on the quote creation page and you should see an option to add an item

**Comment by hillelcoren** [comment]
Hi,

Which version of the mobile app are you using? 

I think it should already be possible to create a new product while creating an invoice. If 'auto update' is enabled on Product > Settings the product should appear in the list when creating the next invoice.

**Comment by Waaiez** [comment]
I was actually hoping this could be a feature on the web app that functions even with 'auto update products' off.
We like to keep auto update off because there are times where we have to factor a discount into our selling price because some of our clients do not want to see an overall discount applied to their quote/invoice.
Keeping auto update off means we can cater to those clients without updating the pricing for our other clients.

Taking a look at the v5 demo, to quick add a new client would be:
* Click new client
![Screenshot_2021-03-15 Invoice Ninja(2)](https://user-images.githubusercontent.com/43832467/111136782-c14b9500-8586-11eb-9b66-6f132801dde5.png)

* Enter any relevant information and click save
![Screenshot_2021-03-15 Invoice Ninja](https://user-images.githubusercontent.com/43832467/111136386-5ef29480-8586-11eb-9c72-2adf53765a56.png)


* After clicking save you are brought back to the quote you were working on with the client information added.
![Screenshot_2021-03-15 Invoice Ninja(1)](https://user-images.githubusercontent.com/43832467/111136400-61ed8500-8586-11eb-9afa-0563a7b933c3.png)

On the v5 demo I don't see a quick way to do this with regards to products. 

By contrast on Sage Accounting when clicking a new line to add an item, there is an option to add a new item.
![Screenshot 2021-03-15 120705](https://user-images.githubusercontent.com/43832467/111137677-bf360600-8587-11eb-8eee-34c62acb8df3.png)

Clicking add new item brings up this popup to add the relevant information
![Screenshot_2021-03-15 Accounting - Process Customer Quote](https://user-images.githubusercontent.com/43832467/111137736-d248d600-8587-11eb-8324-8201d197ce92.png)

Clicking save inserts the newly created item onto the selected line and if I were to search for the product code I used it shows up without having to leave/refresh the page 
![Screenshot_2021-03-15 Accounting - Process Customer Quote(1)](https://user-images.githubusercontent.com/43832467/111138552-bb56b380-8588-11eb-97a6-bc73edf3ad87.png)

**Comment by hillelcoren** [comment]
Thank you for the screenshots, it's very helpful!

One solution may be to ignore the product.discount field when "update products" is enabled?

**Comment by Waaiez** [comment]
Could you elaborate more on the solution? I'm not sure I'm following.

As for our discounts, we do the following:
When we deal with these customers who don't want discounts shown it is because when they submit our quotes for approval they get heavily scrutinized.

For normal customers we would do the following with their quotes, adding the discount to the appropriate field and calling it a day. 
![Screenshot_2021-03-17 Invoice Ninja](https://user-images.githubusercontent.com/43832467/111504149-0cfd6a80-8750-11eb-85e2-3dcfe07cff2a.png)

For our high value customers we go a step further and include their discount in the unit cost and leave the discount field empty. This way when these quotes get looked at, the (unit cost x quantity) will always get the line total and all is good. They still get their discount and they also don't get questions from the higher ups as to why they're receiving a discount
![Screenshot_2021-03-17 Invoice Ninja(1)](https://user-images.githubusercontent.com/43832467/111504730-9d3baf80-8750-11eb-950a-ce0e93a98b23.png)

**Comment by hillelcoren** [comment]
You wrote above "We like to keep auto update off because there are times where we have to factor a discount into our selling price". If the auto-update feature ignored the discount field you could leave the setting on and set discounts when needed.
