### ISSUE TITLE
Login form submit with "enter" key does not work

### ISSUE THREAD

**Issue by nebulade** [invoiceninja/flutter-client#215]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**

5.1.25 (but was with any v5)

**What environment are you running?**
Cloudron

**Describe the bug**
If the focus is in one of the login form input fields, for example after filling the login form (email+password) and then hitting enter instead of clicking the login button, will result in opening a new tab with the URL https://www.invoiceninja.com/

It looks like the actual native browser focus is on some other `a` tag instead.

**Expected behavior**
The form is submitted, same as when clicking the login button

**Additional context**
Happens for me on both Firefox 87.0b9 and Chromium 89.0.4389.9 on Linux

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be resolved in the next

**Comment by nebulade** [comment]
Awesome thanks!
