### ISSUE TITLE
After adding or edit vendor application hangs

### ISSUE THREAD

**Issue by gregoryvanhout** [invoiceninja/flutter-client#216]
**What version of Invoice Ninja are you running?  / v5-latest ( 2021-03-18 )

**What environment are you running?**
Dedicated Hosting ( HETZNER )

**Have you checked log files (storage/logs/) Please provide redacted output**
no added log lines exept version number ( [2021-03-18 11:55:02] production.INFO: latest version = 5.1.27 )

**Have you searched existing issues?**
yes nothing found

** error in console **

main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:4534 Another exception was thrown: Instance of 'minified:lx<void>'
main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:4534 POST: https://finance.gregit.help/api/v1/vendors?
908main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:4534 Another exception was thrown: Instance of 'minified:lx<void>'

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be resolved in the next version
