### ISSUE TITLE
Slow typing in v5

### ISSUE THREAD

**Issue by grokky1** [invoiceninja/flutter-client#218]
# INFO

**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.31

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
not applicable

**Have you searched existing issues?**
yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
see below

**Steps To Reproduce**
use any text editor

**Expected behavior**
normal typing

# DESCRIPTION

I've tried v5 with these setups (extensions disabled):
- windows + edge
- windows + firefox
- linux + firefox
- linux + chrome

In all cases *typing is very slow* - there's a short (roughly 1 second) delay before a character is shown in the ui. I can type a whole line of text, then wait a few moments while the string is printed in the UI. It's not instantaneous.

It's as if the javascript running on the page is VERY aggressive and filtering every keypress.

Has anyone else experienced this?

**Comment by grokky1** [comment]
I use windows when I'm at work (and when I was planning to use InvoiceNinja). Sorry don't know much about or own a mac.

Yes I see this issue in all textboxes, login page, pages in the app, etc. Unfortunately I don't know how to make an animated gif to show you what I mean.

It happens on two computers, so that's why I reached out to find out more. But on the other hand I'm wondering if it's maybe just me - I assumed if this was a known issue with v5 then someone else would have already said something.

Maybe we can close this for now, and see if anyone else stumbles on it?

**Comment by hillelcoren** [comment]
Sorry, I mean to share the Linux version. We hope to have a Windows version in a few months.

https://download.invoiceninja.com/linux

Not sure, is it possible it's a browser plugin?

**Comment by grokky1** [comment]
I assume that's a desktop app - I'll try it when I get a chance and let you know if there's a difference.

Nope I started the browsers with extensions disabled.

**Comment by hillelcoren** [comment]
Yup, correct. Thank! It would be helpful to know if it helps.

Also, do you see the same problem with the sample Flutter web apps?

https://gallery.flutter.dev

**Comment by grokky1** [comment]
I tried that "Reply" app and it seems to work just fine - typing is responsive, no delays.

With invoiceninja I have a suspicion it works slightly better in chrome than other browsers. Just enough to be noticeable. Delay is there but you can ignore it, but the other browsers have a real delay, like I said you type a string of text, and let go of the keyboard, and you can see the characters printed onto the screen even after you stop typing.

---
(By the way, there are other differences between browsers, e.g. in windows firefox, everything is really big and I need to zoom to 80%, but in windows chrome it looks good - but I'll leave that for another thread so as not to confuse this one.)

**Comment by hillelcoren** [comment]
Do you see the same problem in the demo: https://demo.invoiceninja.com

Again, it's critical to know if there is a difference between the login screen and the rest of the app. On the login screen nothing happens when you type, in all other places in the app we retain state while you type which may help explain the problem.

**Comment by grokky1** [comment]
Typing is slow in the demo. I couldn't test the login page as when I click to logout it doesn't do anything?

**Comment by hillelcoren** [comment]
Are you able to test the login page in your installed app?

**Comment by grokky1** [comment]
Good idea! I just tested the login page in my (docker) installed app, and contrary to my comment above, typing is "normal". I can only test in windows right now, but I'll try all the os/browser combinations later.

So it seems that the login page is "normal", but once in the app typing becomes "slow". I wish I could explain better than that :)

**Comment by hillelcoren** [comment]
Thanks, that's useful to know! 

Another place to check in the app is to click the 'contact us' message icon in the lower left corner.

**Comment by grokky1** [comment]
On my installation, typing is "normal" in that contact us widget. Same in the demo site.

**Comment by hillelcoren** [comment]
Thanks for the info, that's helpful to know!

What are the specs of your computer?

I'll try adding a 'performance mode' which I hope will help...

**Comment by grokky1** [comment]
Frankly I'm unsure, but both machines I've tried on are reasonable new. I haven't had similar problems on other sites.

I know nothing of flutter, so maybe I'm going to sound absurd, but the feeling I get is that the keys are being watched by some sort of aggressive javascript event handler which performs some logic on each keypress. If I've seen this sort of behavior in the past it was due to something like that. Just my $0.02.

I still don't understand why I'm the only one to raise this issue. Weird. Maybe it's just me after all!

**Comment by hillelcoren** [comment]
In a sense, that's accurate. Every time you type the app update's its state, if you type a bit wait a few seconds and then refresh the browser your data should still be there.

I'll try to add a flag called 'performance mode' which will debounce these events, this should make the app feel faster but will mean you'll need to wait a micro-second before you can click save.

**Comment by grokky1** [comment]
Let me try understand even though flutter's not my thing - after every user-initiated event (which includes keypresses), the app saves everything to some sort of state store, to prevent data loss.

If that's the case then I agree with you, that definitely explains it. If it were me I'd also debounce keypresses - probably a few seconds of inactivity before updating the state store. Sometimes people type slowly, so <1000ms is too litle, a few seconds (e.g. 2s) is probably safer.

And I'd ensure to debounce only keypress events, nothing else. Well, maybe mouse clicks too if that has any impact on this issue. I imagine some screen you can update lots of data quickly via mouse. I've seen similar perf issues with the mouse but not so bad, I'll try think what screens those were and let you know, can't recall.

Sorry for that if it sounds dumb, like I said i'm not a flutter dev, so consider it pseudo-code :)

**Comment by adamgreenough** [comment]
Wanted to chime in that I have a similar issue on a late-2014 Mac Mini (dual-core i5/8gb memory) in both Chrome and the macOS app. A performance mode sounds like it would be useful and I would love to have the smoother typing over state saving after every keypress.

**Comment by hillelcoren** [comment]
Just to clarify... the app is already debouncing saving the state to disk (which is slow) but currently updates the in-memory state on every key press. In the next version we'll change the app to debounce this as well. I've done some tests, I think we can make this work without having to add a "performance mode" (which I'm reluctant to do).

**Comment by hillelcoren** [comment]
I've applied the change to the 'Details' tab in the edit client form, if you can please try it out in the next release it would be helpful to know if it helps. Assuming it does we'll apply it to the rest of the forms in the app.

**Comment by hillelcoren** [comment]
This change is included in the latest release, please let me know what you think...

**Comment by lonix1** [comment]
Much much better! Thanks for this.

Interestingly it feels more responsive in all textboxes, not just the client-details form.

**Comment by hillelcoren** [comment]
Thanks for the feedback, it's a bug of sorts...

It looks like debouncing has been enabled throughout the app but the solution for pressing enter quickly after changing a value has only been applied in the client form. Note: until it's applied everywhere else if you type quickly you may lose the last few characters, @gincos is kindly helping us out with this 💪

**Comment by grokky1** [comment]
Works awesome for me too!

**Comment by hillelcoren** [comment]
Awesome, great to hear!!

**Comment by lonix1** [comment]
Not quite there yet ... Follow up on this:

If you type quickly in some field, then click "save", it doesn't properly save what you typed. Presumably because it will only save the text after debouncing, and that hasn't occurred yet! So the save event occurs before the end-of-debounce event.

Unsure how it works in flutter, but I recall when using rxjs that there was a way to handle this scenario - that is to take the last event from a stream before saving. Unsure if flutter uses Rx but worth considering. If there's no "FlutterRx", then maybe just interrupt the debounce and take the whole stream. Something like that maybe?

**Comment by hillelcoren** [comment]
Are you using the latest release, this was a bug but it should have been resolved.

**Comment by lonix1** [comment]
Yes I am using 5.1.37 released a little while ago.

I'll put together a test case and get back to you.

**Comment by hillelcoren** [comment]
Do you see this for all records: ie, products/clients/etc?

**Comment by lonix1** [comment]
No, it's kinda strange. I can force this problem but not predictably. But it does fail predictably for custom fields:

- add some custom invoice field
- go to invoice designer, add it to "quote details" and "invoice details"
- create new quote
- type quickly in that field then save

For built-in fields it works, but for that custom field it shows the delay effect I explained above.

The timing is crucial, the bug doesn't always manifest. But for me it does for custom fields.

**Comment by hillelcoren** [comment]
Does it matter if it's in the invoice details or not/is the value missing in the admin portal or on the PDF?

**Comment by hillelcoren** [comment]
Also, can you replicate this problem when creating a product which has a custom field?

**Comment by lonix1** [comment]
where missing: in create/edit quote/invoice screens UI (is that what you mean by admin portal?) AND also in pdf

product with custom field: yes problem manifests there too

**Comment by hillelcoren** [comment]
In the steps you mention "go to invoice designer", is that related to the bug?

I'm not able to reproduce this. Reviewing the code it isn't clear why the custom fields would be any different, are you using a "single-line text" custom field?

**Comment by hillelcoren** [comment]
@grokky1 are you able to reproduce this issue?

**Comment by lonix1** [comment]
> In the steps you mention "go to invoice designer", is that related to the bug?

Yes to add the custom field to the quote/invoice forms

> are you using a "single-line text" custom field?

yes

> I'm not able to reproduce this. Reviewing the code it isn't clear why the custom fields would be any different

Unsure how to proceed... Let me try find some way to make a video or something like that. HAven't done that before, will get back to you.

**Comment by hillelcoren** [comment]
Ok, I think that may be a misunderstanding. The fields set on Settings > Invoice Design determine which fields are added to the PDF, any enabled custom fields will show in the editor. 

A video would be great, thanks! I saw @grokky1 upvoted your comment, curious if he's also seeing this problem...

**Comment by lonix1** [comment]
> Doesn't happen to me now.

Which browser did you test with?

**Comment by hillelcoren** [comment]
@lonix1 are you still seeing a problem? 

In the next release we've adjusted the debounce timer from 1 second to half a second. The problem with the longer value is if parts of the UI change (ie, buttons are activated) there is a delay. In my tests this seems to be a good tradeoff, please let me know if you find otherwise.

**Comment by lonix1** [comment]
@hillelcoren Yes from time to time, but if you lower the debounce period then the problem will theoretically go away (but there is a trade off like you explained).

I do notice though that some fields still "type slowly".

I assume you're referring to the next release, so after I install it I'll let you know if anything changes.

(I assume all these problem go away when a new flutter text editor is available.)

**Comment by hillelcoren** [comment]
Which fields are you seeing the problem in?

I think at this point all pending fixes should be in.

**Comment by lonix1** [comment]
Sorry can't remember - when I notice it aain I'll write it down and update you.

**Comment by hillelcoren** [comment]
Continuing to try to optimize this...

One problem I've noticed is that in some places in the app there can be delays in the UI, for example if you make a change in the settings it will take half a second for the save/cancel buttons to be enabled. 

To correct this I've adjusted the app to send the first event immediately and then denounce future events, in my tests it seems ok but let me know if you see this introduce any problems.

**Comment by lonix1** [comment]
Yes I noticed that too! Can't remember if we discussed it before.

Is that patch in the current or next release?

**Comment by hillelcoren** [comment]
Yeah, I think it makes the app feel slow sometimes 

This change will be in the next release
