### ISSUE TITLE
[Feature Request] Change client when editing quotation/invoice

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/flutter-client#221]
Right now I can edit a quotation or invoice, then change anything. Except the client.

Sometimes you make a mistake, click the wrong item...

If that happens you need to delete the quotation/invoice and create a new one. The deleted number is skipped. Gaps in the invoice number series is not a big deal, but from a tax perspective it's better not to ask for trouble from the tax man (even if you've done nothing wrong).

I've already made this mistake twice, maybe I have fat fingers! :)

**Comment by hillelcoren** [comment]
Thanks for the suggestion!

Sorry, we won't be able to support it. We keep a ledger for each client's balance, if the app supported transferring invoices between clients it would be very complicated to manage and present. 

It's possible we could try to make the process easier and automate the steps required?

**Comment by lonix1** [comment]
Ok so it's a design issue then, not UX. Well I'll need to get used to it then! :disappointed: :smile: 

I'm not sure what you mean by automating the steps?

**Comment by hillelcoren** [comment]
Right now you need to clone the invoice to set a new client and delete the old one, this could be a single action?

**Comment by lonix1** [comment]
That's a nice feature, but I think it would confuse most of your users - it would just mask the underlying problem (not being able to change the client), so maybe let's just leave it as a "hard" design choice - "that's just the way it works". :smile: 

(Incidentally, when you said it can't be done due to the ledger, etc., is that even when the document is in "DRAFT" mode?)

**Comment by hillelcoren** [comment]
Yup, even in draft mode
