### ISSUE TITLE
[Feature Request] Client name defaults when record is only partially complete

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/flutter-client#222]
Most of the time I don't bother populating a client's `Contact.FirstName` and `Contact.LastName` fields as they're the same as `Details.Name`. I just populate the basics: name, email, telephone.

So for example, if I have a client called "Foo Services Ltd" or "John Doe" I won't also populate first/last name. So in a quotation/invoice those show up as "Blank Contact".

If the `Details.Name` is available, but `Contact.FirstName` and `Contact.LastName` are not, is it possible to default to `Details.Name`?

**Comment by hillelcoren** [comment]
I believe that's how the app should currently work. $client.name is the name but $client.display_name is the contact name of the client name.

**Comment by lonix1** [comment]
I've just gone through it again and I found the reverse of what I posted is true: If I fill in the "firstname" / "lastname" then I don't need to fill in "name", and it doesn't show "Blank Contact". But if I do the reverse (as posted above), then it shows "Blank Contact".

Is that what you mean?

I did it that way because that's the first tab that shows (details tab), so it was natural to assume it was a "required" field.

**Comment by hillelcoren** [comment]
@beganovich @turbo124 any thoughts on this/can we avoid showing "Blank Contact"?

**Comment by lonix1** [comment]
If I understand you correctly from above, it's just a display name i.e. just UI, nothing important.

So what do you think of this:
1. if contact.firstname and contact.lastname are populated, use that
2. if details.name is populated, use that (from the first tab shown, so most users like me will assume it is required)
3. if all are populated, default to 1 (backwards compatible)

Right now only 1 applies.

I'm willing to bet most users like me will populate 2 only. Most people don't take time to fill in more than the minimum (name, email, phone). Less friction and faster.

**Comment by turbo124** [comment]
@hillelcoren is the Blank Contact being set in the AP? I don't think we are setting it at all in the API

**Comment by hillelcoren** [comment]
I'm not sure, @lonix1 are you referring to the invoice PDF or in the admin portal?

**Comment by turbo124** [comment]
I can't recreate this, i don't see blank contact anywhere. I can force ```no contact set``` and i have reverted that to client.name

**Comment by lonix1** [comment]
I think this is as @hillelcoren explained above, just UX. It doesn't affect the PDFs.

But to answer your question:
- click to create new quote
- on top left it says "Client"
- click "+"
- choose client
- if client has "firstname"/"lastname" fields then it shows that
- if not, it shows "Blank Contact" (*simple woarkaround is to default to "client.name" which it does have*)

Like I said if this is pure UX, we can close and talk about it in the future when app is more stable.
