### ISSUE TITLE
Run InvoiceNinja without loading 3rd party scripts

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/flutter-client#223]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.1.32-C44

**What environment are you running?**
ZIP

**Have you searched existing issues/requests?**
yes

**Screenshots**
![image](https://user-images.githubusercontent.com/53079668/113052538-9036ab80-91a7-11eb-8112-a6bd910b9ea8.png)

**Additional context**
Currently it appears to impossible to use IN without letting Google know.
Would be nice to have the option to serve the full bundle on your own.

This might also create problems regarding GDPR.
Visitors didn’t consent to load stuff from Google, they aren’t informed what happens with their data processed by Google.

Furthermore, 3rd-party scripts always introduce a possible risk of XSS.

**Comment by hillelcoren** [comment]
Hi,

Thanks for the suggestion! We're working to make the mobile app available through https://www.f-droid.org which had us figure out how to strip out this code, you can see the steps here: 

https://github.com/invoiceninja/flutter-client#steps-to-remove-non-foss-code

@turbo124 most selfhost users won't use the Google features, I think we should have the default admin portal strip out this code and then use a custom version for the hosted platform.

**Comment by hillelcoren** [comment]
This has been implemented
