### ISSUE TITLE
$user variables in email template editor

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/flutter-client#226]
Since they are not currently supported (per invoiceninja/invoiceninja#1251), I believe $user variables should be hidden or removed from the template editor for now. It's confusing to have them there without them working.

**Comment by hillelcoren** [comment]
Hi,

The issue you've linked to is for the v4 app but this repo is for the v5 app where the $user variable is now supported

**Comment by hmnd** [comment]
Oh! Hmm, in that case, this might be an issue for the main repo, since the $user variable doesn't seem to be templated in for me.
