### ISSUE TITLE
Cannot load quote email sending screen in 5.1.35

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/flutter-client#230]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.35 (latest released today)

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
yes

**Have you searched existing issues?**
yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
Cannot show email sending screen for quotes

**Steps To Reproduce**
For invoices it works:
- go to invoices, select one
- click "View PDF" - shows grays screen with loader, then renders
- click "Email Invoice" - shows gray screen, then renders

For quotes it doesn't work:
- go to quotes, select one
- click "View PDF" - shows grays screen with loader, then renders
- click "Email Quote" - shows gray screen, then nothing

**Expected behavior**
For screen to load

**Screenshots**
no

**Additional context**
I opened the devtools in firefox and chromium. The browser receives a successful 200 response for that request with all the relevant data - but does then actually render the screen.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
YES

**Comment by lonix1** [comment]
I'm sorry - hold off on this... it may just be me.

I rolled back to 5.1.34 and I get the same problem (which is strange as it was working an hour ago). Maybe it has something to do with that wasm tweak we discussed in the other thread. I'll revert to an old backup and try again.

**Comment by lonix1** [comment]
Yes when I revert to an old backup of 5.1.34 it works again.

The demo site is using 5.1.35 and it fails like I described above for the email sending screen for: quotes, payments.

**Comment by hillelcoren** [comment]
Thanks for catching this! I've checked in a fix for the next release.
