### ISSUE TITLE
Lowering Tax Rates setting leads to divergent invoices

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/flutter-client#231]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.36-C45

**What environment are you running?**
ZIP

**Have you searched existing issues?**
yes, also reported this unknowingly in invoiceninja/invoiceninja#5292 

**Describe the bug**
Invoices created while tax rates are set to "Two Tax Rates" can have a 2nd tax rate assigned.
When turning that global option back to "One Tax Rate", the 2nd rate will be silently added
- without any notice in the editor
- without any obvious way to remove it.

**Steps To Reproduce**
1. Go to settings > tax settings
2. Set tax rates to "Two Tax Rates"
3. Create an invoice with 2 tax rates
4. Go to settings > tax settings
2. Set tax rates to "One Tax Rates"

**Expected behavior**
Guess the most reasonable thing would be to have invoices with more tax rates than globally specified should still show those "additional" tax rates.

**Screenshots**
![image](https://user-images.githubusercontent.com/53079668/113760624-bc59ab80-9716-11eb-9423-f5f882b33902.png)

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
yes, see screenshot

**Comment by hillelcoren** [comment]
I've checked in a fix, the problem should be resolved in the next release
