### ISSUE TITLE
Taxes aren't applied sometimes

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/flutter-client#232]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.36-C45

**What environment are you running?**
ZIP

**Have you searched existing issues?**
yes

**Describe the bug**
Tax isn't applied at all.

**Steps To Reproduce**
no idea, sorry. It just happens here in this one instance.
Maybe related to invoiceninja/invoiceninja#5292 (another IN v5 instance), where taxes are applied twice sometimes.

**Expected behavior**
Tax (20%) is applied as one would expect.

**Screenshots**
![Clipboard - April 6, 2021 5_16 PM](https://user-images.githubusercontent.com/53079668/113736973-e05cc300-96fd-11eb-9f31-abbf1d89168f.png)

**Additional context**
Only occurs with some invoices.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
no. (But saving invoices is currently broken there anyways `500: Server Error`)

**Comment by hillelcoren** [comment]
@turbo124 @itkfm is this an issue with the PDF or the admin portal?

**Comment by itkfm** [comment]
apparently both PDF and portal don't sum subtotal and VAT for total

**Comment by hillelcoren** [comment]
Is it possible you've enabled inclusive taxes on Settings > Tax Rates?

**Comment by itkfm** [comment]
no, doesn't seem so.
![image](https://user-images.githubusercontent.com/53079668/113907676-f0e06c80-97d5-11eb-8163-6d8cb32c8bc8.png)

**Comment by itkfm** [comment]
Also the calculation seems faulty:
Expected total would be **€313.68**.

```
( ( 1 × 71.4 ) + ( 1 × 190 ) )        = 261.40
( ( 1 × 71.4 ) + ( 1 × 190 ) ) × 1.20 = 313.68

( ( 1 × 71.4 ) + ( 1 × 190 ) ) × 0.20 =  52.28

43.57 ÷ 261.40                        =   0.1667… ≙ ~16,7%
```

**Comment by turbo124** [comment]
this looks like inclusive taxes

**Comment by hillelcoren** [comment]
Are you seeing this problem with new invoices? 

Is it possible you enabled inclusive taxes, created the invoice and then disabled the setting? It could explain this.

**Comment by itkfm** [comment]
Could be the case. I’m afraid, I don’t know.

**Comment by itkfm** [comment]
Any way to check this? Maybe some DB query?

**Comment by hillelcoren** [comment]
I believe it's stored in invoices.uses_inclusive_taxes
