### ISSUE TITLE
Option to have a 12h clock dial instead of the 24h one

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/flutter-client#234]
![image](https://user-images.githubusercontent.com/53079668/113894016-e5864480-97c7-11eb-95b4-8d817d1c2de7.png)

But seriously, a 24h analog clock-style time picker?
This looks ridiculous :laughing:

Jokes aside, I know,  24h clock dials do exist in real life. But I've actually never encountered one myself.
And to be honest, they are **super unhandy** when you aren't used to them.

(I'm aware this is actually an upstream issue: https://github.com/flutter/flutter/issues/65730)

**Comment by hillelcoren** [comment]
Sorry there's nothing we can do to help with this, once it's fixed in the framework it will be automatically corrected in the app. 

I suggest upvoting the linked issue to help ensure it's prioritized.

**Comment by itkfm** [comment]
Upstream issue got closed as invalid :(

**Comment by hillelcoren** [comment]
I've reviewed the code, it doesn't look like it's possible to show 24 hour time in the form fields on the left but 12 hour time in the picker on the right using the native widget.

**Comment by hillelcoren** [comment]
The app is built with Flutter, we're working on a new React based web app which should solve this.
