### ISSUE TITLE
Behavior of "valid until" and "due date" fields

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/flutter-client#236]
Quotes have a "Valid Until" feature, and invoices have "Due Date".

I noticed they work this way:
- go to settings > company > defaults, choose net0/7/14/x for quotes and invoices
- create quote and don't enter a "valid until", or create an invoice and don't enter a "due date", save
- the quote or invoice do not show those fields (in ui or pdf)
- send the document, or "mark as sent"
- now they show those fields (in ui and pdf)

Isn't it more sensible (and doesn't violate the law of least surprise) that if those fields are defined, then when creating a quote/invoice they should be pre-populated with the appropriate values, instead of being blank?

After all, this is precisely the current behavior - those defaults are in effect, UNLESS the user populates those blank fields (on the create quote/invoice form).

So if they're in effect anyway, show them? That would be less surprising and lead to less editing (which is what I've been doing as I couldn't understand why my defaults aren't being applied).

Does any of this make sense, or am I misunderstanding and it's actually by design?

**Comment by lonix1** [comment]
Okay I see an edge case here.

Quotes/invoices can be created but not sent immediately ("draft"). Maybe I want to do a bunch of work on the weekend, and only send on Monday for example.

Then showing the "net0/7/14/x" value in those fields is actually incorrect, as they only apply ONCE SENT. So I now understand the reason for the workflow I documented above.

But it's still confusing. There could be a middle ground. E.g. if the "valid until" is defined as "net7", then instead of showing a blank, rather show "net7". The user can then accept that (in most cases), or remove it and use the date picker.

**Comment by hillelcoren** [comment]
Thanks for the feedback, we'll look into it...

**Comment by hillelcoren** [comment]
Thanks for the suggestion! I've made the change and think it helps, it will be included with the next release.
