### ISSUE TITLE
Email template changes not saved

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/flutter-client#237]
...I'm not sure which repo this belongs in...

**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.41

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
yes

**Have you searched existing issues?**
yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
Cannot save email templates: Reminder1/2/3, Custom3

When I edit and save them, the ui correctly shows my changes. But when I click "send email", and choose them from the dropdown, it still shows the original defaults.

This worked correctly in previous versions.

**Steps To Reproduce**
- goto settings > templates and reminders
- edit these: reminder1/2/3, custom3, save
- note they are saved properly in ui
- go to quotes/invoices and create a new one or choose existing one
- click "send invoice" / "send quote"
- choose template from dropdown
- error: it shows default text

**Expected behavior**
For templates to show correctly when selected in "send email" dropdown

**Screenshots**
no

**Additional context**
I played around with this for a good while, and actually managed to get it to save somehow, once. The rest of the time it didn't work.

If it's not a bug, maybe it's related to a db migration when I updated the version?

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
not allowed in demo site

**Comment by hillelcoren** [comment]
I'm not sure, this is working correctly in my tests.

Is it possible you've overridden the value for the client or group? 

@turbo124 any thoughts on how to debug this?

**Comment by lonix1** [comment]
Like I said yesterday:
>  ...managed to get it to save somehow, once. The rest of the time it didn't work.

I tried again with the same result: I could get it to work sometimes, sometimes not.

**This could be related to browser caching - many problems go away after clearing the cache, especially after upgrades.**

So I just upgraded to the new version, cleared the cache and by magic the problem disappeared.

I'm closing, thanks for trying to repro.

**Comment by lonix1** [comment]
That browser cache problem has bitten me so many times in v5 I'd actually advise using it in the issue template, and also in general when troubleshooting. *Especially after upgrading to a new version.*

The same thing happens in other SPAs - I somtimes get the same problem with Angular apps.

**Comment by lonix1** [comment]
Update: the "Endless Reminders" template cannot be changed - it says "saved", then jumps back to "Invoice", I select it again from the dropdown box, and it shows the old text. Yes even after clearing the cache :)

I don't use it though so doesn't impact me.

**Comment by hillelcoren** [comment]
Sounds like a bug, thanks for catching it!

**Comment by lonix1** [comment]
Works in 5.1.46
Thanks

**Comment by hillelcoren** [comment]
Awesome, glad to hear it!
