### ISSUE TITLE
TAX Columns in product list V5

### ISSUE THREAD

**Issue by GurjinderSingh** [invoiceninja/flutter-client#239]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.1.40-C45
**What environment are you running?**
Docker
**Have you searched existing issues/requests?**
yes
**Screenshots**

![image](https://user-images.githubusercontent.com/3470709/114252451-41d99780-9973-11eb-9000-6e1812d14dc7.png)

**Additional context**

add TAX Column in product list  similar to V4

![image](https://user-images.githubusercontent.com/3470709/114252473-71889f80-9973-11eb-9fe6-028bd199780d.png)

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be fixed in the next version
