### ISSUE TITLE
Task 'Amount' not correctly converted from client curency to home currency

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/flutter-client#241]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.42

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
N/A
**Have you searched existing issues?**
Yes
**Have you reported this to Slack/forum before posting?**
No
**Describe the bug**
Calculated Amount value for tasks is always shown in the home currency, without converting from client's currency. Ie. 1 hrs @ US$100/hr is shown as CA$100.
**Please list the steps to reproduce the issue**
1. Set home currency to CAD or anything other than USD.
2. Create a client with USD as currency.
3. Create a project for client with a set rate.
4. Create task for project and log some time.
**Expected behavior**
Calculated Amount value is displayed in company's currency, converted from client's currency.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Attempted, but it kept resetting clients, projects, and tasks I created or giving me a 500 error.

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be fixed in the next version
