### ISSUE TITLE
Archived Time Tracking Entries are not counted in Project overview

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/flutter-client#243]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.43-C45

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
No

**Have you searched existing issues?**
No

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
As you can see in the Screenshot below, there are 3 Time Tracking Entries for a Project, but somehow, they are not counted any more in the Amount of the Project List, as i have archived them.

**Expected behavior**
Archived Time Tracking Entries shall be counted to the total amount. 
Only exclude deleted Time Tracking Entries from the Amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/114503809-2352f500-9c2e-11eb-8fb9-c240e741da18.png)

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes

**Comment by hillelcoren** [comment]
Thanks, fixed :)
