### ISSUE TITLE
Allow editing tasks seconds

### ISSUE THREAD

**Issue by OXINARF** [invoiceninja/flutter-client#52]
At least on Android, start and stop time fields in tasks only allow to set hours and minutes but not seconds. Also, the task duration can only be set in periods of 15 minutes and not the real duration.

**Comment by hillelcoren** [comment]
You should be able to set the exact start/end times by clicking on the time.

**Comment by OXINARF** [comment]
Here is how it shows on my phone (no way to edit seconds):

![screenshot_20190212-105623](https://user-images.githubusercontent.com/1778527/52630923-6631aa80-2eb5-11e9-82fa-fbdc2669759a.jpg)

**Comment by hillelcoren** [comment]
> Also, the task duration can only be set in periods of 15 minutes and not the real duration.

Is this correct, it looks like you can set the actual duration? Note: you need to press the minutes to be able to adjust them.

**Comment by OXINARF** [comment]
Here is what shows up on my phone (I can't press anywhere else, clicking the duration always shows this):

![screenshot_20190212-113300](https://user-images.githubusercontent.com/1778527/52632673-13a6bd00-2eba-11e9-8cf1-99ec8ea44345.jpg)

**Comment by hillelcoren** [comment]
You can change the times by clicking on the time, using the time selector to set the new time and then clicking ok.

**Comment by OXINARF** [comment]
Yes, sorry, should have been clearer on my initial post. What I meant was that setting the duration would have been a workaround for not being able to set seconds on times, but it's also not possible due to the way duration can be set.

Anyway, this isn't certainly a top priority, but would be nice to be able to do it. Right now I need to go to website to set the exact timing.

**Comment by hillelcoren** [comment]
Thanks, understood

**Comment by hillelcoren** [comment]
This is now supported
