### ISSUE TITLE
Issue with currency decimal digits

### ISSUE THREAD

**Issue by redispade** [invoiceninja/flutter-client#53]
Hello.
I created a custom currency in the database(Albanian Lek, didn't exist on the list). I assigned zero decimal digits and in the main program works correctly. However there is an issue in the mobile app, it adds two decimal digits and messes up with the values. For example I have an invoice where I have value of 1667, VAT(20%) of 333 and total of 2000. Instead on the mobile app I have value of 1666, VAT of 333.4 and a total of 1999.4 Since I have set zero decimal digits, the web app is OK, but the mobile app does not respect that.

**Comment by hillelcoren** [comment]
The app doesn't support zero digit precision, there will likely be other problems with the web app.

**Comment by redispade** [comment]
What kind of problems ? The smallest unit of currency in our country is 1 Lek. I usually round Vat to that(in excess) even when issuing paper invoices.

**Comment by hillelcoren** [comment]
We hope to support this with v2 of the app.

Sorry, I don't remember exactly but in the past we had to change other zero digit currencies to two digits.

**Comment by redispade** [comment]
If the problem is on the mobile app only, it's ok for now, it's a minor issue, as long as the server side is good.
I am using it self hosted and seriously considering whitelabeling. If you need to test anything feel free to drop a message

**Comment by hillelcoren** [comment]
This has been implemented in the v5 app
