### ISSUE TITLE
iOS Paste not possible

### ISSUE THREAD

**Issue by arillus-at** [invoiceninja/flutter-client#54]
Try to paste text in some fields. Not Wirkung. Got error:
NoSuchMethodError: The getter ‚pasteButtonLabel‘ called on Null.
Receiver: null
Tried Calling: pasteButtonLabel

**Comment by hillelcoren** [comment]
Which language are you using in the web app?

**Comment by arillus-at** [comment]
Both are German. APP and Website

**Comment by hillelcoren** [comment]
If you get a chance can you please let us know if you're still seeing this problem in the latest version.
