### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by alexanderadam** [invoiceninja/flutter-client#64]
I wasn't able to find [InvoiceNinja on F-Droid](https://search.f-droid.org/?q=invoice+ninja) but it would be nice to have it published there as well. And my guess is that F-Droid has probably a higher percentage of users that might be interested in InvoiceNinja than the other stores. :wink: 

I am not sure how "open" [this license](https://github.com/invoiceninja/flutter-mobile/blob/master/LICENSE.txt) is and whether it, and its dependencies are open enough to publish it on [F-Droid](https://search.f-droid.org/?q=invoice+ninja).
The [requirements for F-Droid are naturally strict](https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included) but maybe the InvoiceNinja doesn't need any/much changes.

PS: thank you for your work :open_hands:

**Comment by hillelcoren** [comment]
Thanks for the suggestions, it's the first time I've heard of F-Droid.

It looks like the next step would be submitting the app here: https://gitlab.com/fdroid/rfp/issues

The AAL license is approved by the OSI: https://opensource.org/licenses/alphabetical

**Comment by skylarmt** [comment]
At the very least, is there some way to download the APK officially?

**Comment by hillelcoren** [comment]
The APK can be download here: https://download.invoiceninja.com/apk

**Comment by skylarmt** [comment]
I've uploaded that official APK to my F-Droid repository at https://repo.netsyms.com, I'll check back in from time to time and update as necessary.

**Comment by hillelcoren** [comment]
Thanks for setting it up! On the play store we're switching from using apk's to app bundles., would the app bundle work for you or is the apk better?

**Comment by skylarmt** [comment]
F-Droid doesn't support app bundles, just the regular APKs that actually get installed on a device.

**Comment by skylarmt** [comment]
> The APK can be download here: https://download.invoiceninja.com/apk

That link now just serves the latest InvoiceNinja .zip download, not the APK.

**Comment by hillelcoren** [comment]
We don't have APKs available for the current version but we plan to make the available for v5

**Comment by fazlerabbi37** [comment]
@hillelcoren, did you manage to open an issue on the RFP repo on F-Droid?

**Comment by hillelcoren** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1549

Note: we only plan to submit v5

**Comment by hillelcoren** [comment]
The app has been submitted, I imagine it will take a few days to appear in the store
