### ISSUE TITLE
New App Unable to Add Multiple Company?

### ISSUE THREAD

**Issue by lesliechw** [invoiceninja/flutter-client#74]
Hi all,

I updated the mobile app but I'm unable to find way to add another company. Is the new app not allow multiple self hosted Invoice Ninja with different URL?

Please advice, thank you.

**Comment by hillelcoren** [comment]
Hi,

You need to use the web app to create the company, you can see the option by clicking your name in the top right.

**Comment by lesliechw** [comment]
Hi,

You mean, the app only can access company that is under the same self host system?

I'm pretty sure the previous version of the app can add different self host system under different domain name.

Please correct me if I'm wrong. Please advice, thank you.

**Comment by hillelcoren** [comment]
The mobile app can access all companies.

In order to add a company you need to use the web app.

**Comment by hillelcoren** [comment]
This has been implemented in the v5 app
