### ISSUE TITLE
Login fails (iOS 13.1.2)

### ISSUE THREAD

**Issue by RosemaryOrchard** [invoiceninja/flutter-client#86]
On iOS the login screen (self hosted) fails. If I can manage to fill out the credentials (see below) then tapping login empties all fields. As far as I can see from the access logs on my server no connection attempt is made. 

Password manager integration only works 50% of the time to fill out the fields. The rest of the time you can select a login but nothing happens. Additionally switching away from the app (such as to your password manager) and back empties all the credential fields, after a period of a few minutes this might be wise from a security perspective but inside of a minute it is an exercise in frustration.

**Comment by hillelcoren** [comment]
Are you using the iOS beta?

**Comment by RosemaryOrchard** [comment]
Yes, 13.1.2 is a beta right now.

**Comment by hillelcoren** [comment]
Another user reported a similar issue. I think the problem with the beta is it will keep logging you out of the app. You may want to consider enabling Google login in the web app on Settings > User Details to make it easier to login.

**Comment by jasonehines** [comment]
I'm seeing the same issue with the Public Beta 13.2 (17B5084A)
