### ISSUE TITLE
List/Save Invoice dost not work

### ISSUE THREAD

**Issue by voeurnchy** [invoiceninja/flutter-client#92]
1. go to invoice section it still keep loading.
1. create new invoice but can't save
![photo_2019-10-21_23-45-09](https://user-images.githubusercontent.com/16317127/67225169-ebb22500-f45c-11e9-9e78-38b0bc9d3b12.jpg)
![photo_2019-10-21_23-45-12](https://user-images.githubusercontent.com/16317127/67225171-ec4abb80-f45c-11e9-85f8-19a2c0b908c2.jpg)

**Comment by hillelcoren** [comment]
Which versions of the web and mobile app are you using?

**Comment by voeurnchy** [comment]
They are the latest version
web: just clone from master
mobile: your app in play store.

**Comment by hillelcoren** [comment]
Thanks, I think I may see the problem. Try changing this line from (int) to (bool).

https://github.com/invoiceninja/invoiceninja/blob/master/app/Ninja/Transformers/InvoiceTransformer.php#L124

**Comment by voeurnchy** [comment]
Yes. It's working. Thanks

**Comment by hillelcoren** [comment]
Glad to hear it, we'll include a fix with the next version.
