### ISSUE TITLE
Close app since view or download Invoice PDF

### ISSUE THREAD

**Issue by voeurnchy** [invoiceninja/flutter-client#93]
mobile: app from playstore
web:  master branch

**Comment by hillelcoren** [comment]
Which version of Android are you using?

To view the PDF invoice you may need to use the 'Client Portal' link.

**Comment by voeurnchy** [comment]
Android version: 9
it already enable
<img width="655" alt="Screen Shot 2019-10-24 at 8 30 09 AM" src="https://user-images.githubusercontent.com/16317127/67445915-e0b3ec00-f638-11e9-8331-003d388efa53.png">

or you refer to `Display the invoice in an iFrame on your own website` ?
