### ISSUE TITLE
Loader not loading in the center

### ISSUE THREAD

**Issue by gopalindians** [invoiceninja/flutter-client#96]
Loader not loading in the center.

![Screenshot_2019-10-28-20-09-51-589_com invoiceninja flutter](https://user-images.githubusercontent.com/1937433/67687925-0c2f3180-f9bf-11e9-974d-1b45d51d82e1.png)

On almost everything screen loader is not showing in the center.

Screen Width: 393 pixels
Screen Height: 822 pixels

Device: [Redmi note 7 pro](https://www.mi.com/in/redmi-note-7-pro/specs/)

**Comment by hjJunior** [comment]
Hi @hillelcoren I'd like to handle it, can I?

**Comment by hillelcoren** [comment]
Thanks for the offer! This should be resolved in the latest versio
