### ISSUE TITLE
Uploading some photos in documents in iOS

### ISSUE THREAD

**Issue by Kopono** [invoiceninja/flutter-client#99]
On iOS 12. When attempting to upload a photo from the camera roll, it gives me an error stating that it "Tried to construct class "DocumentEntity" with null field "width". This is forbidden; to allow it, mark "width" with @nullable.

**Comment by hillelcoren** [comment]
Which exact versions of the web and mobile app are you using?

**Comment by Kopono** [comment]
Hey hillelcoren,

I'm currently using the latest version of Invoice Ninja App (1.9) and Web (v4.5.13). On iOS 12.4 right now.

**Comment by hillelcoren** [comment]
Thanks, updating to the latest version of the web app should fix it

**Comment by Kopono** [comment]
Ah understood, thanks very much hillelcoren!
